{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-15T21:19:00.000+0000",
      "latitude": 50.745099797148754,
      "estimatedRestoration": "2022-02-16T09:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JM4878'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JM4878",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.74488,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.70881
            },
            {
              "py/object": "Point",
              "latitude": 50.745099797148754,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.7081773021447122
            },
            {
              "py/object": "Point",
              "latitude": 50.74529,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.70756
            }
          ],
          "subCodes": [
            "BH23 5AS",
            "BH23 5AU"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JM4878",
      "name": "BH23 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH23 5AS",
        "BH23 5AU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.70881,
              50.74488
            ],
            [
              -1.7081773021447122,
              50.745099797148754
            ],
            [
              -1.70756,
              50.74529
            ],
            [
              -1.70881,
              50.74488
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-15T23:59:00.000+0000",
      "UUID": "534b6328-20a2-4f83-9e7c-9a4b900c0c4c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7081773021447122,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-15T23:22:00.000+0000",
      "latitude": 50.95700512529343,
      "estimatedRestoration": "2022-02-16T03:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JM4897'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JM4897",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.9569,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61577
            },
            {
              "py/object": "Point",
              "latitude": 50.95761,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61434
            },
            {
              "py/object": "Point",
              "latitude": 50.95713,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61402
            },
            {
              "py/object": "Point",
              "latitude": 50.95686,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61396
            },
            {
              "py/object": "Point",
              "latitude": 50.95607,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61466
            },
            {
              "py/object": "Point",
              "latitude": 50.9569,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.61577
            }
          ],
          "subCodes": [
            "BA21 5RS",
            "BA21 5UJ",
            "BA21 5UP",
            "BA21 5UQ",
            "BA21 5UR",
            "BA21 5US"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JM4897",
      "name": "BA21 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA21 5RS",
        "BA21 5UJ",
        "BA21 5UP",
        "BA21 5UQ",
        "BA21 5UR",
        "BA21 5US"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -2.61577,
              50.9569
            ],
            [
              -2.61434,
              50.95761
            ],
            [
              -2.61402,
              50.95713
            ],
            [
              -2.61396,
              50.95686
            ],
            [
              -2.61466,
              50.95607
            ],
            [
              -2.61577,
              50.9569
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-02-16T00:30:00.000+0000",
      "UUID": "8660d934-9b39-43f0-b7fe-9f94cc4e1982",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.6145325636257537,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-16T00:31:00.000+0000",
      "latitude": 51.40125241011498,
      "estimatedRestoration": "2022-02-16T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JM4916'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JM4916",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.40124,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.73106
            }
          ],
          "name": "RG12 0XB",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JM4916",
      "name": "RG12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG12 0XB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.7310802894421771,
          51.40125241011498
        ],
        "type": "Point"
      },
      "UUID": "c6310117-58dd-47ce-bd14-6399a5e93d72",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7310802894421771,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-02-15T20:00:00.000+0000",
      "latitude": 60.761827841095275,
      "estimatedRestoration": "2022-02-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JM4856'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JM4856",
      "reference": "JM4856",
      "name": "ZE2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "ZE2 9DS",
        "ZE2 9DY"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.8622972535531122,
          60.761827841095275
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-02-16T08:30:00.000+0000",
      "UUID": "7625b20a-fe63-43bd-9f3f-11f9592e1910",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8622972535531122,
      "resolved": false
    }
  ]
}
