{
  "Faults": [
    {
      "latitude": 51.47180314381788,
      "type": "LV",
      "reference": "KY2419",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-06-01T12:15:00.000+0000",
      "affectedCustomerCount": 37,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "173e3eeb-dbe6-4682-9ab1-e068127d6346",
      "minLongitude": -0.9771,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9745655117249442,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-01T21:50:00.000+0000",
      "estimatedRestoration": "2023-06-02T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY2419'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY2419",
      "maxLongitude": -0.9723,
      "minLatitude": 51.469,
      "name": "RG4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG4 7QY",
        "RG4 7RA",
        "RG4 7RB",
        "RG4 7SD",
        "RG4 7SS",
        "RG4 7ST",
        "RG4 7SU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.9771,
              51.475
            ],
            [
              -0.9723,
              51.475
            ],
            [
              -0.9723,
              51.469
            ],
            [
              -0.9771,
              51.469
            ],
            [
              -0.9771,
              51.475
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-01T12:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.475,
      "etrUpdate": true
    },
    {
      "latitude": 51.432092675698016,
      "type": "LV",
      "reference": "KY2780",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-06-01T17:21:00.000+0000",
      "affectedCustomerCount": 2,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "c08c6347-3d48-4ebb-92c2-6333d02b2bf5",
      "minLongitude": -0.5075,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.5050896851378827,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-01T15:41:00.000+0000",
      "estimatedRestoration": "2023-06-02T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY2780'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY2780",
      "maxLongitude": -0.5018,
      "minLatitude": 51.4312,
      "name": "TW18 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW18 2AW",
        "TW18 2FD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.5075,
              51.4329
            ],
            [
              -0.5018,
              51.4329
            ],
            [
              -0.5018,
              51.4312
            ],
            [
              -0.5075,
              51.4312
            ],
            [
              -0.5075,
              51.4329
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-01T17:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4329,
      "etrUpdate": true
    },
    {
      "latitude": 50.802159431145675,
      "type": "HV",
      "reference": "KY3039",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-06-02T03:25:00.000+0000",
      "affectedCustomerCount": 7,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9afc90ee-47cc-4ab6-946a-e4d029d24f47",
      "minLongitude": -0.6754,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6744035588283923,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-02T02:41:00.000+0000",
      "estimatedRestoration": "2023-06-02T09:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY3039'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY3039",
      "maxLongitude": -0.6707,
      "minLatitude": 50.8003,
      "name": "PO22 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO22 9SL",
        "PO22 9UL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6754,
              50.8039
            ],
            [
              -0.6707,
              50.8039
            ],
            [
              -0.6707,
              50.8003
            ],
            [
              -0.6754,
              50.8003
            ],
            [
              -0.6754,
              50.8039
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-02T03:40:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8039,
      "etrUpdate": true
    },
    {
      "latitude": 50.62197255693583,
      "type": "LV",
      "reference": "KY3007",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "c66261c7-88d3-4f63-9a2d-f5923850f58c",
      "minLongitude": -2.474,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4722395665828136,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-01T23:39:00.000+0000",
      "estimatedRestoration": "2023-06-02T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY3007'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY3007",
      "maxLongitude": -2.4676,
      "minLatitude": 50.6203,
      "name": "DT4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT4 0ED"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.474,
              50.6231
            ],
            [
              -2.4676,
              50.6231
            ],
            [
              -2.4676,
              50.6203
            ],
            [
              -2.474,
              50.6203
            ],
            [
              -2.474,
              50.6231
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-02T06:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.6231,
      "etrUpdate": true
    },
    {
      "latitude": 51.0682466678908,
      "type": "HV",
      "reference": "KY3138",
      "etaUpdate": true,
      "affectedCustomerCount": 289,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "f85104a1-d3af-4ed0-af12-5a6c336876f2",
      "minLongitude": -1.6642,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.610987640594934,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-02T06:23:00.000+0000",
      "estimatedRestoration": "2023-06-02T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY3138'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY3138",
      "maxLongitude": -1.5836,
      "minLatitude": 51.0012,
      "name": "SP5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SP5 1DD",
        "SP5 1JN",
        "SP5 1JP",
        "SP5 1JW",
        "SP5 1JX",
        "SP5 1JY",
        "SP5 1JZ",
        "SP5 1LA",
        "SP5 1LB",
        "SP5 1LD",
        "SP5 1LE",
        "SP5 1LN",
        "SP5 1LP",
        "SP5 1LR",
        "SP5 1LS",
        "SP5 1LW",
        "SP5 1LX",
        "SP5 1LY",
        "SP5 1NA",
        "SP5 1NB",
        "SP5 1NF",
        "SP5 1NG",
        "SP5 1NH",
        "SP5 1NL",
        "SP5 1NN",
        "SP5 1NP",
        "SP5 1NR",
        "SP5 1NS",
        "SP5 1NT",
        "SP5 1NU",
        "SP5 1NW",
        "SP5 1NX",
        "SP5 1NY",
        "SP5 1PA",
        "SP5 1PB",
        "SP5 1PD",
        "SP5 1QB",
        "SP5 1TH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.6642,
              51.0632
            ],
            [
              -1.5836,
              51.0632
            ],
            [
              -1.5836,
              51.0012
            ],
            [
              -1.6642,
              51.0012
            ],
            [
              -1.6642,
              51.0632
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.0632,
      "etrUpdate": true
    },
    {
      "latitude": 56.77136156650187,
      "type": "HV",
      "reference": "KY3096",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "93e8613e-adfe-4fb4-b6b4-3a8ac763552f",
      "minLongitude": -3.84,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.8186538064558264,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-02T04:29:00.000+0000",
      "estimatedRestoration": "2023-06-02T08:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY3096'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY3096",
      "maxLongitude": -3.6959,
      "minLatitude": 56.7516,
      "name": "PH18 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PH16 5LT",
        "PH18",
        "PH18 5TR",
        "PH18 5TS",
        "PH18 5TT",
        "PH18 5TU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.84,
              56.8192
            ],
            [
              -3.6959,
              56.8192
            ],
            [
              -3.6959,
              56.7516
            ],
            [
              -3.84,
              56.7516
            ],
            [
              -3.84,
              56.8192
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-02T05:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.8192,
      "etrUpdate": true
    },
    {
      "latitude": 56.72999563431694,
      "type": "LV",
      "reference": "KY3097",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "6b0766b9-6bb5-4c99-8cf3-504bb168ad82",
      "minLongitude": -2.6571,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.654941047244211,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-06-02T04:28:00.000+0000",
      "estimatedRestoration": "2023-06-02T07:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KY3097'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KY3097",
      "maxLongitude": -2.6527,
      "minLatitude": 56.7283,
      "name": "DD9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD9 6DZ",
        "DD9 6HG",
        "DD9 6HN",
        "DD9 6HQ",
        "DD9 6HS",
        "DD9 7AH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6571,
              56.7319
            ],
            [
              -2.6527,
              56.7319
            ],
            [
              -2.6527,
              56.7283
            ],
            [
              -2.6571,
              56.7283
            ],
            [
              -2.6571,
              56.7319
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-06-02T05:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.7319,
      "etrUpdate": true
    }
  ]
}
