{
  "Faults": [
    {
      "latitude": 50.817548147285926,
      "type": "LV",
      "reference": "KV3711",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-29T22:30:00.000+0000",
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "ba01de0d-7e33-4e56-bfa8-80ff3d3e3a76",
      "minLongitude": -1.0042,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9795887455296053,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-29T21:34:00.000+0000",
      "estimatedRestoration": "2023-04-30T16:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3711'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3711",
      "maxLongitude": -0.9705,
      "minLatitude": 50.8099,
      "name": "PO11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO11 0LE",
        "PO11 0LF",
        "PO11 0LH",
        "PO11 0LJ",
        "PO11 0LL",
        "PO11 0LR",
        "PO11 0LT"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0042,
              50.8227
            ],
            [
              -0.9705,
              50.8227
            ],
            [
              -0.9705,
              50.8099
            ],
            [
              -1.0042,
              50.8099
            ],
            [
              -1.0042,
              50.8227
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-29T22:40:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8227,
      "etrUpdate": true
    },
    {
      "latitude": 51.35338864463416,
      "type": "LV",
      "reference": "KV3849",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-30T07:15:00.000+0000",
      "affectedCustomerCount": 9,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "fa566eee-509e-45c3-8070-2de1b21a4473",
      "minLongitude": -1.9976,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9956429579303772,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T06:12:00.000+0000",
      "estimatedRestoration": "2023-04-30T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3849'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3849",
      "maxLongitude": -1.9936,
      "minLatitude": 51.3521,
      "name": "SN10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN10",
        "SN10 1DU",
        "SN10 1EB",
        "SN10 1EX",
        "SN10 1FG",
        "SN10 1HT",
        "SN10 1HU",
        "SN10 1JG",
        "SN10 1JQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9976,
              51.3558
            ],
            [
              -1.9936,
              51.3558
            ],
            [
              -1.9936,
              51.3521
            ],
            [
              -1.9976,
              51.3521
            ],
            [
              -1.9976,
              51.3558
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T07:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3558,
      "etrUpdate": true
    },
    {
      "latitude": 51.71619587499931,
      "type": "PSI",
      "reference": "216089",
      "etaUpdate": true,
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "20838a1b-1165-4c10-ade1-f3d2f0effcaf",
      "minLongitude": -1.9666,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9648659366569243,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T07:30:00.000+0000",
      "estimatedRestoration": "2023-04-30T16:30:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '216089'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/216089",
      "maxLongitude": -1.9624,
      "minLatitude": 51.7156,
      "name": "GL7 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GL7 2PF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9666,
              51.7169
            ],
            [
              -1.9624,
              51.7169
            ],
            [
              -1.9624,
              51.7156
            ],
            [
              -1.9666,
              51.7156
            ],
            [
              -1.9666,
              51.7169
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7169,
      "etrUpdate": true
    },
    {
      "latitude": 51.53510498542129,
      "type": "HV",
      "reference": "KV3928",
      "etaUpdate": true,
      "affectedCustomerCount": 48,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "abfdb06a-be7b-423a-bf1a-014914c0bbc2",
      "minLongitude": -1.0796,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0448433258287686,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T10:20:00.000+0000",
      "estimatedRestoration": "2023-04-30T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3928'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3928",
      "maxLongitude": -1.0174,
      "minLatitude": 51.5185,
      "name": "RG8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG8 0NT",
        "RG8 0NU",
        "RG8 0NX",
        "RG8 0NY",
        "RG8 0PH",
        "RG8 0QS",
        "RG8 0QT",
        "RG8 0SR",
        "RG8 0UB",
        "RG8 0UD",
        "RG8 0UE",
        "RG8 0UH",
        "RG8 0UJ",
        "RG8 0UL",
        "RG8 0UN",
        "RG8 0UP",
        "RG8 0UR",
        "RG8 0UT",
        "RG8 0UU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0796,
              51.5459
            ],
            [
              -1.0174,
              51.5459
            ],
            [
              -1.0174,
              51.5185
            ],
            [
              -1.0796,
              51.5185
            ],
            [
              -1.0796,
              51.5459
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T11:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5459,
      "etrUpdate": true
    },
    {
      "latitude": 50.902335931685094,
      "type": "HV",
      "reference": "KV3880",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-30T09:00:00.000+0000",
      "affectedCustomerCount": 181,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "b95f9b36-1431-41b3-ad69-015d4e398c6f",
      "minLongitude": -2.2069,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.167343607183907,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T07:55:00.000+0000",
      "estimatedRestoration": "2023-04-30T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3880'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3880",
      "maxLongitude": -2.0638,
      "minLatitude": 50.8673,
      "name": "DT11 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT11 8PU",
        "DT11 8RX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.2069,
              50.918
            ],
            [
              -2.0638,
              50.918
            ],
            [
              -2.0638,
              50.8673
            ],
            [
              -2.2069,
              50.8673
            ],
            [
              -2.2069,
              50.918
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.918,
      "etrUpdate": true
    },
    {
      "latitude": 50.74505099719263,
      "type": "LV",
      "reference": "KV4010",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-30T14:25:00.000+0000",
      "affectedCustomerCount": 37,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "6f534271-6925-4a2d-a896-c2106c1a4731",
      "minLongitude": -1.6254,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5954290643737759,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T13:34:00.000+0000",
      "estimatedRestoration": "2023-04-30T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV4010'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV4010",
      "maxLongitude": -1.5907,
      "minLatitude": 50.7381,
      "name": "SO41 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO41 0DB",
        "SO41 0EH",
        "SO41 0JX",
        "SO41 0JZ",
        "SO41 0LA",
        "SO41 0LD",
        "SO41 0LL",
        "SO41 0LN",
        "SO41 0LW",
        "SO41 0UA",
        "SO41 0ZA",
        "SO41 0ZB",
        "SO41 0ZD",
        "SO41 0ZF",
        "SO41 0ZG",
        "SO41 0ZH",
        "SO41 0ZJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.6254,
              50.7516
            ],
            [
              -1.5907,
              50.7516
            ],
            [
              -1.5907,
              50.7381
            ],
            [
              -1.6254,
              50.7381
            ],
            [
              -1.6254,
              50.7516
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T14:10:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7516,
      "etrUpdate": true
    },
    {
      "latitude": 51.516186093439025,
      "type": "LV",
      "reference": "KV4025",
      "etaUpdate": true,
      "affectedCustomerCount": 7,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e51e9168-3359-49b0-a1d4-1976fecf4942",
      "minLongitude": -1.2599,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2572771351254832,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T14:20:00.000+0000",
      "estimatedRestoration": "2023-04-30T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV4025'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV4025",
      "maxLongitude": -1.2561,
      "minLatitude": 51.5154,
      "name": "RG20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG20 6PP",
        "RG20 7PF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.2599,
              51.5189
            ],
            [
              -1.2561,
              51.5189
            ],
            [
              -1.2561,
              51.5154
            ],
            [
              -1.2599,
              51.5154
            ],
            [
              -1.2599,
              51.5189
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T15:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5189,
      "etrUpdate": true
    },
    {
      "latitude": 50.84336300084347,
      "type": "LV",
      "reference": "KV3999",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-04-30T13:40:00.000+0000",
      "affectedCustomerCount": 17,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d90b0d0d-5949-4dc6-8350-d850997e24b8",
      "minLongitude": -1.803,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.7929539635243679,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T13:00:00.000+0000",
      "estimatedRestoration": "2023-04-30T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3999'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3999",
      "maxLongitude": -1.7878,
      "minLatitude": 50.8298,
      "name": "BH24 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH24 1EJ",
        "BH24 1EQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.803,
              50.8451
            ],
            [
              -1.7878,
              50.8451
            ],
            [
              -1.7878,
              50.8298
            ],
            [
              -1.803,
              50.8298
            ],
            [
              -1.803,
              50.8451
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8451,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T15:54:00.000+0000",
      "latitude": 51.45001479230755,
      "estimatedRestoration": "2023-04-30T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV4057'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV4057",
      "reference": "KV4057",
      "etaUpdate": true,
      "affectedCustomerCount": 11,
      "name": "TW19 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "TW19 7SL",
        "TW19 7SS",
        "TW19 7ST",
        "TW19 7SY",
        "TW19 7TD"
      ],
      "location": {
        "coordinates": [
          -0.4709721804211098,
          51.45001479230755
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T16:45:00.000+0000",
      "UUID": "daef6f0a-fd4b-460e-96be-513ee97d9dc4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -0.4709721804211098,
      "resolved": false
    },
    {
      "latitude": 51.36027259987902,
      "type": "HV",
      "reference": "KV4070",
      "etaUpdate": true,
      "affectedCustomerCount": 2557,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "23d779aa-88b0-4fec-b4d5-bedb63742ee0",
      "minLongitude": -2.1689,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.133103772962091,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T16:07:00.000+0000",
      "estimatedRestoration": "2023-04-30T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV4070'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV4070",
      "maxLongitude": -2.1094,
      "minLatitude": 51.344,
      "name": "BA14 & SN12 Areas",
      "otherUpdate": true,
      "affectedAreas": [
        "BA14 6JR",
        "BA14 6JT",
        "BA14 6JX",
        "SN12",
        "SN12 6AH",
        "SN12 6AJ",
        "SN12 6AL",
        "SN12 6AQ",
        "SN12 6AR",
        "SN12 6AS",
        "SN12 6AT",
        "SN12 6AU",
        "SN12 6AX",
        "SN12 6AY",
        "SN12 6AZ",
        "SN12 6BA",
        "SN12 6BB",
        "SN12 6BD",
        "SN12 6BE",
        "SN12 6BF",
        "SN12 6BG",
        "SN12 6BN",
        "SN12 6BU",
        "SN12 6BX",
        "SN12 6BY",
        "SN12 6DB",
        "SN12 6DF",
        "SN12 6DG",
        "SN12 6DH",
        "SN12 6DJ",
        "SN12 6DL",
        "SN12 6DN",
        "SN12 6DP",
        "SN12 6DR",
        "SN12 6DS",
        "SN12 6DT",
        "SN12 6DU",
        "SN12 6DW",
        "SN12 6DX",
        "SN12 6DY",
        "SN12 6DZ",
        "SN12 6EA",
        "SN12 6EB",
        "SN12 6ED",
        "SN12 6EE",
        "SN12 6EF",
        "SN12 6EG",
        "SN12 6EH",
        "SN12 6EJ",
        "SN12 6EL",
        "SN12 6EN",
        "SN12 6EQ",
        "SN12 6ER",
        "SN12 6ET",
        "SN12 6EU",
        "SN12 6EW",
        "SN12 6EY",
        "SN12 6FA",
        "SN12 6FB",
        "SN12 6FD",
        "SN12 6FE",
        "SN12 6FF",
        "SN12 6FG",
        "SN12 6FH",
        "SN12 6FJ",
        "SN12 6FL",
        "SN12 6FQ",
        "SN12 6GH",
        "SN12 6HP",
        "SN12 6HR",
        "SN12 6HS",
        "SN12 6HT",
        "SN12 6HU",
        "SN12 6HX",
        "SN12 6HY",
        "SN12 6HZ",
        "SN12 6JA",
        "SN12 6JB",
        "SN12 6JD",
        "SN12 6JE",
        "SN12 6JF",
        "SN12 6JG",
        "SN12 6JH",
        "SN12 6JJ",
        "SN12 6JP",
        "SN12 6JW",
        "SN12 6LW",
        "SN12 6ND",
        "SN12 6QE",
        "SN12 6QF",
        "SN12 6QN",
        "SN12 6QP",
        "SN12 6QR",
        "SN12 6QS",
        "SN12 6QU",
        "SN12 6QY",
        "SN12 6QZ",
        "SN12 6RA",
        "SN12 6RP",
        "SN12 6SG",
        "SN12 6SJ",
        "SN12 6SN",
        "SN12 6SP",
        "SN12 6SS",
        "SN12 6ST",
        "SN12 6SU",
        "SN12 6SW",
        "SN12 6SX",
        "SN12 6SY",
        "SN12 6SZ",
        "SN12 6TA",
        "SN12 6TB",
        "SN12 6TD",
        "SN12 6TE",
        "SN12 6TF",
        "SN12 6TG",
        "SN12 6TH",
        "SN12 6TJ",
        "SN12 6TP",
        "SN12 6TQ",
        "SN12 6TR",
        "SN12 6TS",
        "SN12 6TT",
        "SN12 6TU",
        "SN12 6TW",
        "SN12 6TX",
        "SN12 6TY",
        "SN12 6TZ",
        "SN12 6UA",
        "SN12 6UD",
        "SN12 6UE",
        "SN12 6UF",
        "SN12 6UG",
        "SN12 6UH",
        "SN12 6UJ",
        "SN12 6UL",
        "SN12 6UQ",
        "SN12 6UT",
        "SN12 6UU",
        "SN12 6UW",
        "SN12 6UX",
        "SN12 6UY",
        "SN12 6UZ",
        "SN12 6WB",
        "SN12 6WG",
        "SN12 6WQ",
        "SN12 6WS",
        "SN12 6XA",
        "SN12 6XB",
        "SN12 6XD",
        "SN12 6XN",
        "SN12 6XP",
        "SN12 6XR",
        "SN12 6XS",
        "SN12 6XT",
        "SN12 6XU",
        "SN12 6XW",
        "SN12 6XX",
        "SN12 6XY",
        "SN12 6YH",
        "SN12 7SJ",
        "SN12 8BU",
        "SN12 8LH",
        "SN12 8PB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1689,
              51.3773
            ],
            [
              -2.1094,
              51.3773
            ],
            [
              -2.1094,
              51.344
            ],
            [
              -2.1689,
              51.344
            ],
            [
              -2.1689,
              51.3773
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3773,
      "etrUpdate": true
    },
    {
      "latitude": 51.45069914360837,
      "type": "LV",
      "reference": "KV4059",
      "etaUpdate": true,
      "affectedCustomerCount": 39,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a6324836-b1d4-4443-951d-0cbb54318a1d",
      "minLongitude": -0.384,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.46142196087672055,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T15:54:00.000+0000",
      "estimatedRestoration": "2023-04-30T19:15:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV4059'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV4059",
      "maxLongitude": -0.3825,
      "minLatitude": 51.4779,
      "name": "TW19 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW19 7AA",
        "TW19 7AD",
        "TW19 7AE",
        "TW19 7BE",
        "TW19 7BJ",
        "TW19 7SB",
        "TW19 7SJ",
        "TW19 7SL",
        "TW19 7SQ",
        "TW19 7ST",
        "TW5 0AE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.384,
              51.4792
            ],
            [
              -0.3825,
              51.4792
            ],
            [
              -0.3825,
              51.4779
            ],
            [
              -0.384,
              51.4779
            ],
            [
              -0.384,
              51.4792
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4792,
      "etrUpdate": true
    },
    {
      "latitude": 55.6019310439029,
      "type": "HV",
      "reference": "KV3943",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "c7e92644-81f2-4643-b611-0f930766defe",
      "minLongitude": -5.6935,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.682320973468116,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-04-30T10:43:00.000+0000",
      "estimatedRestoration": "2023-04-30T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KV3943'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KV3943",
      "maxLongitude": -5.5623,
      "minLatitude": 55.5714,
      "name": "PA29 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA29 6XD",
        "PA29 6XE",
        "PA29 6XF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -5.6935,
              55.6601
            ],
            [
              -5.5623,
              55.6601
            ],
            [
              -5.5623,
              55.5714
            ],
            [
              -5.6935,
              55.5714
            ],
            [
              -5.6935,
              55.6601
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-04-30T11:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.6601,
      "etrUpdate": true
    }
  ]
}
