{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T02:11:00.000+0000",
      "latitude": 51.453023390775854,
      "estimatedRestoration": "2022-05-22T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5865'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5865",
      "reference": "JT5865",
      "engineerOnSiteTime": "2022-05-21T23:45:00.000+0000",
      "name": "RG30 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG30 4NT",
        "RG30 4NU",
        "RG30 4NX",
        "RG30 4RB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.0376483320196306,
          51.453023390775854
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-21T23:55:00.000+0000",
      "UUID": "e1fc9f4b-460b-4f50-9e0a-1e66b270ea04",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0376483320196306,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T03:27:00.000+0000",
      "latitude": 50.85795285467899,
      "estimatedRestoration": "2022-05-22T13:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5891'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5891",
      "reference": "JT5891",
      "engineerOnSiteTime": "2022-05-22T04:25:00.000+0000",
      "name": "SO31 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO31 6PQ",
        "SO31 6PR",
        "SO31 6PS",
        "SO31 6XS",
        "SO31 6XW",
        "SO31 6XX",
        "SO31 6XZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.2784771090300193,
          50.85795285467899
        ],
        "type": "Point"
      },
      "UUID": "f16973fb-837a-4a27-9f96-12c9b32447fc",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2784771090300193,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T08:00:00.000+0000",
      "latitude": 51.61438611597956,
      "estimatedRestoration": "2022-05-22T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5933'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5933",
      "reference": "JT5933",
      "name": "HP9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "HP9 2BS",
        "HP9 2BZ",
        "HP9 2DE",
        "HP9 2DF",
        "HP9 2DQ",
        "HP9 2PZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.6393392876787454,
          51.61438611597956
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T09:00:00.000+0000",
      "UUID": "05a229f1-6815-44e4-bd8f-0f310cdf15a2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6393392876787454,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T01:26:00.000+0000",
      "latitude": 58.59570012132322,
      "estimatedRestoration": "2022-05-22T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5876'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5876",
      "reference": "JT5876",
      "engineerOnSiteTime": "2022-05-22T03:00:00.000+0000",
      "name": "KW14 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW14 7BQ",
        "KW14 7HF",
        "KW14 7HH",
        "KW14 7JA",
        "KW14 8BD",
        "KW14 8BH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.5226619404723944,
          58.59570012132322
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T03:00:00.000+0000",
      "UUID": "fffb39a6-fbb2-4255-b5ff-935bf2f3d393",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.5226619404723944,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T03:06:00.000+0000",
      "latitude": 57.70269172997128,
      "estimatedRestoration": "2022-05-22T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5886'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5886",
      "reference": "JT5886",
      "engineerOnSiteTime": "2022-05-22T04:45:00.000+0000",
      "name": "IV17 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV17 0AD",
        "IV17 0AJ",
        "IV17 0AL",
        "IV17 0TS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.230997239871496,
          57.70269172997128
        ],
        "type": "Point"
      },
      "UUID": "5f3a8124-c4c9-4486-ac7b-57a5abd03371",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.230997239871496,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-05-22T07:10:00.000+0000",
      "latitude": 57.48163988147479,
      "estimatedRestoration": "2022-05-22T11:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JT5911'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JT5911",
      "reference": "JT5911",
      "name": "IV3 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV3 8LU",
        "IV3 8PT",
        "IV3 8TT"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.251011938116965,
          57.48163988147479
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-05-22T08:30:00.000+0000",
      "UUID": "fab915fb-368a-4c1f-bc22-59cb8b3970e4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.251011938116965,
      "resolved": false
    }
  ]
}
