{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-13T23:15:00.000+0000",
      "latitude": 50.71321669965348,
      "estimatedRestoration": "2022-08-15T05:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY2750'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY2750",
      "reference": "JY2750",
      "maxLongitude": -1.7753,
      "engineerOnSiteTime": "2022-08-14T09:10:00.000+0000",
      "minLatitude": 50.711,
      "name": "BH15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH15 1HA",
        "BH15 1JD",
        "BH15 1ZA",
        "BH15 1ZB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9942,
              50.7326
            ],
            [
              -1.7753,
              50.7326
            ],
            [
              -1.7753,
              50.711
            ],
            [
              -1.9942,
              50.711
            ],
            [
              -1.9942,
              50.7326
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-14T08:00:00.000+0000",
      "UUID": "47e4fc5e-7826-4322-b682-dea22f84f398",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.9942,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.7326,
      "longitude": -1.990741669705031,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-14T19:46:00.000+0000",
      "latitude": 51.09964003788347,
      "estimatedRestoration": "2022-08-15T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3054'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3054",
      "reference": "JY3054",
      "maxLongitude": -0.691,
      "engineerOnSiteTime": "2022-08-14T21:00:00.000+0000",
      "minLatitude": 51.0977,
      "name": "GU27 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU27 2DF",
        "GU27 2DG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7037,
              51.1038
            ],
            [
              -0.691,
              51.1038
            ],
            [
              -0.691,
              51.0977
            ],
            [
              -0.7037,
              51.0977
            ],
            [
              -0.7037,
              51.1038
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-14T21:00:00.000+0000",
      "UUID": "f9cdb66c-07cf-4950-8a32-d48ef687ad28",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.7037,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.1038,
      "longitude": -0.6958647188191375,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-14T21:29:00.000+0000",
      "latitude": 51.582061859253805,
      "estimatedRestoration": "2022-08-15T09:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3111'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3111",
      "reference": "JY3111",
      "maxLongitude": -0.7603,
      "engineerOnSiteTime": "2022-08-14T22:01:00.000+0000",
      "minLatitude": 51.5803,
      "name": "SL7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SL7 1TT",
        "SL7 1TU",
        "SL7 1TX",
        "SL7 1TY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7643,
              51.584
            ],
            [
              -0.7603,
              51.584
            ],
            [
              -0.7603,
              51.5803
            ],
            [
              -0.7643,
              51.5803
            ],
            [
              -0.7643,
              51.584
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-14T22:15:00.000+0000",
      "UUID": "a1cb0982-0900-4518-add9-fd24da42af33",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.7643,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.584,
      "longitude": -0.762133238831874,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-14T20:47:00.000+0000",
      "latitude": 50.802027030595454,
      "estimatedRestoration": "2022-08-15T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3081'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3081",
      "reference": "JY3081",
      "maxLongitude": -1.9813,
      "engineerOnSiteTime": "2022-08-14T21:25:00.000+0000",
      "minLatitude": 50.7997,
      "name": "BH21 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BH21 1AG",
        "BH21 1AS",
        "BH21 1AT",
        "BH21 1AU",
        "BH21 1HZ",
        "BH21 1UP",
        "BH21 1UR",
        "BH21 1UW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9871,
              50.8065
            ],
            [
              -1.9813,
              50.8065
            ],
            [
              -1.9813,
              50.7997
            ],
            [
              -1.9871,
              50.7997
            ],
            [
              -1.9871,
              50.8065
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "f7aca99d-15ed-4e3a-ba5b-f36532749a72",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.9871,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "2bab9328-70d9-431d-be55-e8110ca7e933"
      ],
      "maxLatitude": 50.8065,
      "longitude": -1.9840976857166006,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T03:46:00.000+0000",
      "latitude": 51.486252519242235,
      "estimatedRestoration": "2022-08-15T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3172'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3172",
      "reference": "JY3172",
      "maxLongitude": -0.2435,
      "minLatitude": 51.4842,
      "name": "W4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "W4 2PA",
        "W4 2PD",
        "W4 2PH",
        "W4 2PJ",
        "W4 2PP",
        "W4 2QB",
        "W4 2QE",
        "W4 2QG",
        "W4 2QH",
        "W4 2QJ",
        "W4 2QL",
        "W4 2SR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.2554,
              51.489
            ],
            [
              -0.2435,
              51.489
            ],
            [
              -0.2435,
              51.4842
            ],
            [
              -0.2554,
              51.4842
            ],
            [
              -0.2554,
              51.489
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T05:00:00.000+0000",
      "UUID": "e0b8500b-d312-40d0-8ceb-1c0737f11073",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.2554,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.489,
      "longitude": -0.2508902564244347,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T03:54:00.000+0000",
      "latitude": 50.87209380826214,
      "estimatedRestoration": "2022-08-15T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3177'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3177",
      "reference": "JY3177",
      "maxLongitude": -0.9657,
      "minLatitude": 50.8714,
      "name": "PO9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO9 5JS",
        "PO9 5RD",
        "PO9 5RE",
        "PO9 5RG"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.9682,
              50.8733
            ],
            [
              -0.9657,
              50.8733
            ],
            [
              -0.9657,
              50.8714
            ],
            [
              -0.9682,
              50.8714
            ],
            [
              -0.9682,
              50.8733
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T04:40:00.000+0000",
      "UUID": "34a0c575-f95a-46bb-9d3e-1712b8e99d38",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.9682,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8733,
      "longitude": -0.9668155050796708,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T04:35:00.000+0000",
      "latitude": 50.82089496915379,
      "estimatedRestoration": "2022-08-15T08:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3192'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3192",
      "reference": "JY3192",
      "maxLongitude": -1.1629,
      "minLatitude": 50.8188,
      "name": "PO13 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO13 0JT",
        "PO13 0LB",
        "PO13 0LD",
        "PO13 0WX",
        "PO13 0XL",
        "PO13 0ZB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1676,
              50.8249
            ],
            [
              -1.1629,
              50.8249
            ],
            [
              -1.1629,
              50.8188
            ],
            [
              -1.1676,
              50.8188
            ],
            [
              -1.1676,
              50.8249
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T05:45:00.000+0000",
      "UUID": "1ebd9e83-519a-4b53-adb7-2d9c778c11ee",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.1676,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8249,
      "longitude": -1.1653062071374563,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T02:56:00.000+0000",
      "latitude": 50.8686168614848,
      "estimatedRestoration": "2022-08-15T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3156'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3156",
      "reference": "JY3156",
      "maxLongitude": -1.0289,
      "minLatitude": 50.8679,
      "name": "PO7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO7 5UY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0316,
              50.8691
            ],
            [
              -1.0289,
              50.8691
            ],
            [
              -1.0289,
              50.8679
            ],
            [
              -1.0316,
              50.8679
            ],
            [
              -1.0316,
              50.8691
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T04:30:00.000+0000",
      "UUID": "1f3cb286-bb5d-4fe5-86b3-6ad65715e2c8",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.0316,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8691,
      "longitude": -1.0300749677919225,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T02:49:00.000+0000",
      "latitude": 57.2422179864572,
      "estimatedRestoration": "2022-08-15T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3150'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3150",
      "reference": "JY3150",
      "maxLongitude": -2.4388,
      "minLatitude": 57.2229,
      "name": "AB51 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB51",
        "AB51 5LH",
        "AB51 5LX",
        "AB51 5LY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4822,
              57.2503
            ],
            [
              -2.4388,
              57.2503
            ],
            [
              -2.4388,
              57.2229
            ],
            [
              -2.4822,
              57.2229
            ],
            [
              -2.4822,
              57.2503
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T04:00:00.000+0000",
      "UUID": "d2d8f10e-b9b8-4acf-aeb4-eaaa08403daa",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.4822,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 57.2503,
      "longitude": -2.457599111302084,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T03:21:00.000+0000",
      "latitude": 56.714064447676336,
      "estimatedRestoration": "2022-08-15T07:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3166'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3166",
      "reference": "JY3166",
      "maxLongitude": -2.4737,
      "minLatitude": 56.6687,
      "name": "DD10 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD10 9EF",
        "DD10 9EG",
        "DD10 9JS",
        "DD10 9LE",
        "DD10 9LF",
        "DD10 9LG",
        "DD10 9LH",
        "DD10 9LJ",
        "DD10 9LL",
        "DD10 9LN",
        "DD10 9LQ",
        "DD10 9LS",
        "DD10 9LT",
        "DD10 9LW",
        "DD10 9LX",
        "DD10 9LY",
        "DD10 9TJ",
        "DD10 9TL",
        "DD9 6TU",
        "DD9 6TY",
        "DD9 6TZ",
        "DD9 6UA",
        "DD9 6UB",
        "DD9 6UD",
        "DD9 6UE",
        "DD9 6UF",
        "DD9 6UH",
        "DD9 6UJ",
        "DD9 6UP",
        "DD9 7AF",
        "DD9 7PN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6532,
              56.7532
            ],
            [
              -2.4737,
              56.7532
            ],
            [
              -2.4737,
              56.6687
            ],
            [
              -2.6532,
              56.6687
            ],
            [
              -2.6532,
              56.7532
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T05:00:00.000+0000",
      "UUID": "32779f07-7674-47e7-af57-143938eaef9e",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.6532,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 56.7532,
      "longitude": -2.5515985243036434,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T02:06:00.000+0000",
      "latitude": 56.41606590827789,
      "estimatedRestoration": "2022-08-15T06:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3186'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3186",
      "reference": "JY3186",
      "maxLongitude": -3.1137,
      "minLatitude": 56.3889,
      "name": "PH2 & PH14 Areas",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH14 9QN",
        "PH14 9QP",
        "PH14 9QW",
        "PH2 7TA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.1809,
              56.4355
            ],
            [
              -3.1137,
              56.4355
            ],
            [
              -3.1137,
              56.3889
            ],
            [
              -3.1809,
              56.3889
            ],
            [
              -3.1809,
              56.4355
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "29c0eb36-42c6-4bcf-a984-a5f3651fd3ca",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -3.1809,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 56.4355,
      "longitude": -3.16069620338559,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-15T02:45:00.000+0000",
      "latitude": 56.38331548867615,
      "estimatedRestoration": "2022-08-15T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY3199'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY3199",
      "reference": "JY3199",
      "maxLongitude": -3.4338,
      "minLatitude": 56.3758,
      "name": "PH2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH2 0AS",
        "PH2 0AT",
        "PH2 0AU",
        "PH2 0AW",
        "PH2 0AX",
        "PH2 0BN",
        "PH2 0BT",
        "PH2 0BU",
        "PH2 0BW",
        "PH2 0BX",
        "PH2 0BY",
        "PH2 0BZ",
        "PH2 0DA",
        "PH2 0DB",
        "PH2 0DE",
        "PH2 0DH",
        "PH2 0DJ",
        "PH2 0DL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.4535,
              56.3863
            ],
            [
              -3.4338,
              56.3863
            ],
            [
              -3.4338,
              56.3758
            ],
            [
              -3.4535,
              56.3758
            ],
            [
              -3.4535,
              56.3863
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-08-15T04:00:00.000+0000",
      "UUID": "a4f747d5-13ae-4461-aff3-8febd1ba4255",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -3.4535,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 56.3863,
      "longitude": -3.4423796295302895,
      "resolved": false
    }
  ]
}
