{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-20T18:03:00.000+0000",
      "latitude": 51.393638163484745,
      "estimatedRestoration": "2022-04-22T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS0518'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS0518",
      "reference": "JS0518",
      "engineerOnSiteTime": "2022-04-20T19:10:00.000+0000",
      "name": "GU25 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU25 4NE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.6077212618157147,
          51.393638163484745
        ],
        "type": "Point"
      },
      "UUID": "2ce562b2-b543-4cd3-bbd1-864232e1974a",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6077212618157147,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-22T00:00:00.000+0000",
      "latitude": 51.52827527530414,
      "estimatedRestoration": "2022-04-22T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS1013'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS1013",
      "reference": "JS1013",
      "engineerOnSiteTime": "2022-04-21T19:41:00.000+0000",
      "name": "UB4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB4 9AJ",
        "UB4 9AL",
        "UB4 9AN",
        "UB4 9AU",
        "UB4 9AW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.4002783249149042,
          51.52827527530414
        ],
        "type": "Point"
      },
      "UUID": "c7d2313a-0563-4aed-ad19-0cddc5c3ffb2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.4002783249149042,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-04-21T20:47:00.000+0000",
      "latitude": 50.89500221697261,
      "estimatedRestoration": "2022-04-22T04:15:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JS1053'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JS1053",
      "reference": "JS1053",
      "engineerOnSiteTime": "2022-04-21T21:10:00.000+0000",
      "name": "PO9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO9 6AE",
        "PO9 6AF",
        "PO9 6BS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.9642185855483751,
          50.89500221697261
        ],
        "type": "Point"
      },
      "UUID": "2b16a52b-def6-4ac0-9ebb-3d24f220560f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9642185855483751,
      "resolved": false
    }
  ]
}
