{
  "Faults": [
    {
      "latitude": 51.49977145401303,
      "type": "LV",
      "reference": "MV4346",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T11:25:00.000+0000",
      "affectedCustomerCount": 41,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "2e642f88-e8b6-412a-9ead-4014b4dfcd63",
      "minLongitude": -0.3832,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3800832818159411,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T09:20:00.000+0000",
      "estimatedRestoration": "2023-11-16T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV4346'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV4346",
      "maxLongitude": -0.378,
      "minLatitude": 51.4987,
      "name": "UB2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "UB2 4EA",
        "UB2 4ED",
        "UB2 4EE",
        "UB2 4EG",
        "UB2 4EH",
        "UB2 4EQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3832,
              51.501
            ],
            [
              -0.378,
              51.501
            ],
            [
              -0.378,
              51.4987
            ],
            [
              -0.3832,
              51.4987
            ],
            [
              -0.3832,
              51.501
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T11:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.501,
      "etrUpdate": true
    },
    {
      "latitude": 50.87914846256376,
      "type": "LV",
      "reference": "MV4927",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T15:00:00.000+0000",
      "affectedCustomerCount": 210,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "954b7635-430f-4683-a18a-aa3a13f9ded6",
      "minLongitude": -1.8823,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8794861503950961,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T14:10:00.000+0000",
      "estimatedRestoration": "2023-11-15T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV4927'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV4927",
      "maxLongitude": -1.8712,
      "minLatitude": 50.8695,
      "name": "BH31 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH31 6AE",
        "BH31 6DP",
        "BH31 6DR",
        "BH31 6DS",
        "BH31 6DT",
        "BH31 6DY",
        "BH31 6DZ",
        "BH31 6HD",
        "BH31 6HT",
        "BH31 6YE",
        "BH31 6YF",
        "BH31 6YR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8823,
              50.8819
            ],
            [
              -1.8712,
              50.8819
            ],
            [
              -1.8712,
              50.8695
            ],
            [
              -1.8823,
              50.8695
            ],
            [
              -1.8823,
              50.8819
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T15:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8819,
      "etrUpdate": true
    },
    {
      "latitude": 51.40051766707532,
      "type": "LV",
      "reference": "MV5072",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T17:15:00.000+0000",
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0678d25c-da50-4b9f-82ae-3726fdbf6869",
      "minLongitude": -0.6378,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6321956560996774,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T15:36:00.000+0000",
      "estimatedRestoration": "2023-11-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5072'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5072",
      "maxLongitude": -0.6242,
      "minLatitude": 51.3983,
      "name": "SL5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL5 0LR",
        "SL5 0LX",
        "SL5 0NB",
        "SL5 0NE",
        "SL5 0NF",
        "SL5 0NG",
        "SL5 0NQ",
        "SL5 0NS",
        "SL5 0NT",
        "SL5 0NX",
        "SL5 0NZ",
        "SL5 0PA",
        "SL5 0QH",
        "SL5 0QQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6378,
              51.4043
            ],
            [
              -0.6242,
              51.4043
            ],
            [
              -0.6242,
              51.3983
            ],
            [
              -0.6378,
              51.3983
            ],
            [
              -0.6378,
              51.4043
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T17:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4043,
      "etrUpdate": true
    },
    {
      "latitude": 51.486363561997145,
      "type": "LV",
      "reference": "MV3253",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-14T13:50:00.000+0000",
      "affectedCustomerCount": 2,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "4a83b626-52c6-4d0a-82c2-ee155f22f033",
      "minLongitude": -0.3264,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3237522858695663,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T14:00:00.000+0000",
      "estimatedRestoration": "2023-11-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV3253'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV3253",
      "maxLongitude": -0.3194,
      "minLatitude": 51.4855,
      "name": "TW8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW8 9EX",
        "TW8 9EZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3264,
              51.4889
            ],
            [
              -0.3194,
              51.4889
            ],
            [
              -0.3194,
              51.4855
            ],
            [
              -0.3264,
              51.4855
            ],
            [
              -0.3264,
              51.4889
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4889,
      "etrUpdate": true
    },
    {
      "latitude": 51.375722457719725,
      "type": "LV",
      "reference": "MV5396",
      "etaUpdate": true,
      "affectedCustomerCount": 10,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "fdde1007-6337-4b15-8549-7f7e26f01102",
      "minLongitude": -0.6712,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.670147780291595,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T22:56:00.000+0000",
      "estimatedRestoration": "2023-11-16T08:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5396'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5396",
      "maxLongitude": -0.6689,
      "minLatitude": 51.3746,
      "name": "GU20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU20 6NE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6712,
              51.3768
            ],
            [
              -0.6689,
              51.3768
            ],
            [
              -0.6689,
              51.3746
            ],
            [
              -0.6712,
              51.3746
            ],
            [
              -0.6712,
              51.3768
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-16T00:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3768,
      "etrUpdate": true
    },
    {
      "latitude": 51.40312819440528,
      "type": "LV",
      "reference": "MV4687",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T13:10:00.000+0000",
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e079af97-9d51-4c8a-a8f3-fcc4ae487345",
      "minLongitude": -0.8507,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8482823702166127,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T12:02:00.000+0000",
      "estimatedRestoration": "2023-11-16T06:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV4687'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV4687",
      "maxLongitude": -0.8457,
      "minLatitude": 51.402,
      "name": "RG41 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG41 2GY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8507,
              51.4041
            ],
            [
              -0.8457,
              51.4041
            ],
            [
              -0.8457,
              51.402
            ],
            [
              -0.8507,
              51.402
            ],
            [
              -0.8507,
              51.4041
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4041,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:04:00.000+0000",
      "latitude": 50.7766575795912,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5504'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5504",
      "reference": "MV5504",
      "maxLongitude": -2.5611,
      "etaUpdate": true,
      "minLatitude": 50.775,
      "name": "DT2 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 0BL",
        "DT2 0BN",
        "DT2 0BT",
        "DT2 0BU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.5693,
              50.7786
            ],
            [
              -2.5611,
              50.7786
            ],
            [
              -2.5611,
              50.775
            ],
            [
              -2.5693,
              50.775
            ],
            [
              -2.5693,
              50.7786
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "70ef602e-8f67-4050-b3fd-8a48146cdaaf",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.5693,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.7786,
      "etrUpdate": true,
      "longitude": -2.5669923419559866,
      "resolved": false
    },
    {
      "latitude": 50.839458447186644,
      "type": "LV",
      "reference": "MV5517",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "c5976ac0-498f-4801-8813-20fc2affb2d5",
      "minLongitude": -2.6102,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.605303402987288,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:07:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5517'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5517",
      "maxLongitude": -2.5942,
      "minLatitude": 50.8326,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 0JP",
        "DT2 0JS",
        "DT2 0JW",
        "DT2 0JX",
        "DT2 0JY",
        "DT2 0JZ",
        "DT2 0LE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6102,
              50.8442
            ],
            [
              -2.5942,
              50.8442
            ],
            [
              -2.5942,
              50.8326
            ],
            [
              -2.6102,
              50.8326
            ],
            [
              -2.6102,
              50.8442
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8442,
      "etrUpdate": true
    },
    {
      "latitude": 50.80977595427582,
      "type": "LV",
      "reference": "MV5562",
      "etaUpdate": true,
      "affectedCustomerCount": 5,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "e8b5e96d-8043-46bd-8d49-dc28c66b4cce",
      "minLongitude": -2.4879,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.481270609461346,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:07:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:10:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5562'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5562",
      "maxLongitude": -2.4794,
      "minLatitude": 50.8083,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 7JE",
        "DT2 7JX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4879,
              50.8137
            ],
            [
              -2.4794,
              50.8137
            ],
            [
              -2.4794,
              50.8083
            ],
            [
              -2.4879,
              50.8083
            ],
            [
              -2.4879,
              50.8137
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8137,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:07:00.000+0000",
      "latitude": 50.809295140178854,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5574'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5574",
      "reference": "MV5574",
      "maxLongitude": -2.4527,
      "etaUpdate": true,
      "minLatitude": 50.8021,
      "name": "DT2 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 7GD",
        "DT2 7GW",
        "DT2 7JG",
        "DT2 7JJ",
        "DT2 7JL",
        "DT2 7JN",
        "DT2 7TS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4758,
              50.8197
            ],
            [
              -2.4527,
              50.8197
            ],
            [
              -2.4527,
              50.8021
            ],
            [
              -2.4758,
              50.8021
            ],
            [
              -2.4758,
              50.8197
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "975bedf7-9dad-44fb-9ad2-1a6b1fe25fa4",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.4758,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8197,
      "etrUpdate": true,
      "longitude": -2.471288149238694,
      "resolved": false
    },
    {
      "latitude": 50.80657184617004,
      "type": "HV",
      "reference": "MV5500",
      "etaUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "ba95e490-0cf2-4e22-bc87-6f710f8be62a",
      "minLongitude": -2.6285,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.466449666249531,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:06:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5500'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5500",
      "maxLongitude": -2.24,
      "minLatitude": 50.6655,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA22 9TL",
        "DT2 7JF",
        "DT2 7JL",
        "DT2 7JN",
        "DT2 7JP",
        "DT2 7JQ",
        "DT2 7JW",
        "DT2 7LA",
        "DT2 7LE",
        "DT2 7TS",
        "DT2 8DD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6285,
              50.9186
            ],
            [
              -2.24,
              50.9186
            ],
            [
              -2.24,
              50.6655
            ],
            [
              -2.6285,
              50.6655
            ],
            [
              -2.6285,
              50.9186
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9186,
      "etrUpdate": true
    },
    {
      "latitude": 50.79295530956629,
      "type": "LV",
      "reference": "MV5559",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "be9d36e8-7f66-42ec-800f-2f95f79d8916",
      "minLongitude": -2.4879,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4691232412043793,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:06:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5559'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5559",
      "maxLongitude": -2.3879,
      "minLatitude": 50.7051,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 7GT",
        "DT2 7GU",
        "DT2 7JF",
        "DT2 7JR",
        "DT2 7JS",
        "DT2 7JU",
        "DT2 7JW",
        "DT2 7JX",
        "DT2 7JY",
        "DT2 7LF",
        "DT2 7RZ",
        "DT2 8AD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4879,
              50.8137
            ],
            [
              -2.3879,
              50.8137
            ],
            [
              -2.3879,
              50.7051
            ],
            [
              -2.4879,
              50.7051
            ],
            [
              -2.4879,
              50.8137
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8137,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:06:00.000+0000",
      "latitude": 50.774253771228466,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5515'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5515",
      "reference": "MV5515",
      "maxLongitude": -2.4005,
      "etaUpdate": true,
      "minLatitude": 50.7626,
      "name": "DT2 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 7TB",
        "DT2 7TD",
        "DT2 7TE",
        "DT2 7TF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4254,
              50.7811
            ],
            [
              -2.4005,
              50.7811
            ],
            [
              -2.4005,
              50.7626
            ],
            [
              -2.4254,
              50.7626
            ],
            [
              -2.4254,
              50.7811
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "5d81f2c6-dd9e-45c1-a6d8-34f12e4be935",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.4254,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.7811,
      "etrUpdate": true,
      "longitude": -2.4059673040215244,
      "resolved": false
    },
    {
      "latitude": 50.79448683680145,
      "type": "LV",
      "reference": "MV5541",
      "etaUpdate": true,
      "affectedCustomerCount": 10,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "82f61596-69b5-4d9d-b070-42ccb5bd0879",
      "minLongitude": -2.5318,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5234229894019986,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:05:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:10:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5541'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5541",
      "maxLongitude": -2.5216,
      "minLatitude": 50.7923,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 9NY",
        "DT2 9PB",
        "DT2 9PD",
        "DT2 9TH"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.5318,
              50.7985
            ],
            [
              -2.5216,
              50.7985
            ],
            [
              -2.5216,
              50.7923
            ],
            [
              -2.5318,
              50.7923
            ],
            [
              -2.5318,
              50.7985
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7985,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:04:00.000+0000",
      "latitude": 50.73275255657948,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5505'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5505",
      "reference": "MV5505",
      "maxLongitude": -2.2993,
      "etaUpdate": true,
      "minLatitude": 50.6689,
      "name": "DT2 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2",
        "DT2 0AA",
        "DT2 0AB",
        "DT2 0AE",
        "DT2 0AH",
        "DT2 0AJ",
        "DT2 0AL",
        "DT2 0AP",
        "DT2 0AR",
        "DT2 0AS",
        "DT2 0AT",
        "DT2 0AU",
        "DT2 0AW",
        "DT2 0AX",
        "DT2 0AY",
        "DT2 0AZ",
        "DT2 0BA",
        "DT2 0BD",
        "DT2 0BE",
        "DT2 0BG",
        "DT2 0BQ",
        "DT2 0BS",
        "DT2 0BT",
        "DT2 0BU",
        "DT2 0BX",
        "DT2 0BY",
        "DT2 0BZ",
        "DT2 0DA",
        "DT2 0DX",
        "DT2 0DY",
        "DT2 0DZ",
        "DT2 0EA",
        "DT2 0EB",
        "DT2 0ED",
        "DT2 0EE",
        "DT2 0EF",
        "DT2 0NF",
        "DT2 0QL",
        "DT2 7EJ",
        "DT2 9AA",
        "DT2 9AB",
        "DT2 9AD",
        "DT2 9AE",
        "DT2 9AF",
        "DT2 9AG",
        "DT2 9AH",
        "DT2 9AJ",
        "DT2 9AL",
        "DT2 9AN",
        "DT2 9AP",
        "DT2 9AQ",
        "DT2 9AR",
        "DT2 9AS",
        "DT2 9AT",
        "DT2 9AU",
        "DT2 9AW",
        "DT2 9AX",
        "DT2 9AY",
        "DT2 9AZ",
        "DT2 9BA",
        "DT2 9BB",
        "DT2 9BD",
        "DT2 9BE",
        "DT2 9BG",
        "DT2 9BH",
        "DT2 9BJ",
        "DT2 9BL",
        "DT2 9BN",
        "DT2 9BQ",
        "DT2 9BW",
        "DT2 9BX",
        "DT2 9DP",
        "DT2 9DR",
        "DT2 9DW",
        "DT2 9ED",
        "DT2 9EE",
        "DT2 9EF",
        "DT2 9EH",
        "DT2 9ER",
        "DT2 9ES",
        "DT2 9EX",
        "DT2 9HN",
        "DT2 9HP",
        "DT2 9HR",
        "DT2 9HS",
        "DT2 9HT",
        "DT2 9HU",
        "DT2 9HW",
        "DT2 9JB",
        "DT2 9NQ",
        "DT2 9TE",
        "DT2 9TF",
        "DT3 4JZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6637,
              50.8737
            ],
            [
              -2.2993,
              50.8737
            ],
            [
              -2.2993,
              50.6689
            ],
            [
              -2.6637,
              50.6689
            ],
            [
              -2.6637,
              50.8737
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "8ce77088-846f-4f47-ae96-f31d620ec429",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.6637,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8737,
      "etrUpdate": true,
      "longitude": -2.6050884314810485,
      "resolved": false
    },
    {
      "latitude": 50.7942728452587,
      "type": "LV",
      "reference": "MV5486",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "99dc73f7-89b9-4b60-a442-4d7bc11f9ad6",
      "minLongitude": -2.582,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5782581952009855,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T05:59:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5486'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5486",
      "maxLongitude": -2.5656,
      "minLatitude": 50.7847,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 0JH",
        "DT2 0JJ",
        "DT2 0JL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.582,
              50.8004
            ],
            [
              -2.5656,
              50.8004
            ],
            [
              -2.5656,
              50.7847
            ],
            [
              -2.582,
              50.7847
            ],
            [
              -2.582,
              50.8004
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8004,
      "etrUpdate": true
    },
    {
      "latitude": 50.712759503669325,
      "type": "LV",
      "reference": "MV5483",
      "etaUpdate": true,
      "affectedCustomerCount": 31,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d050e53f-4907-435a-bf10-50a52efb6f91",
      "minLongitude": -2.3528,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.336062453509803,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T05:57:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5483'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5483",
      "maxLongitude": -2.3257,
      "minLatitude": 50.6933,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 8GE",
        "DT2 8GF",
        "DT2 8TP",
        "DT2 8TT",
        "DT2 8TU",
        "DT2 8TW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3528,
              50.7525
            ],
            [
              -2.3257,
              50.7525
            ],
            [
              -2.3257,
              50.6933
            ],
            [
              -2.3528,
              50.6933
            ],
            [
              -2.3528,
              50.7525
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7525,
      "etrUpdate": true
    }
  ]
}
