{
  "Faults": [
    {
      "latitude": 51.19842649536481,
      "type": "HV",
      "reference": "KN4043",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-10T15:20:00.000+0000",
      "affectedCustomerCount": 452,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a614b331-0df1-48da-9a3e-8ace0646ec67",
      "minLongitude": -2.176,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1697753540539733,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-10T14:08:00.000+0000",
      "estimatedRestoration": "2023-02-11T13:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4043'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4043",
      "maxLongitude": -2.1639,
      "minLatitude": 51.1944,
      "name": "BA12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA12 9LB",
        "BA12 9LD",
        "BA12 9LE",
        "BA12 9LF",
        "BA12 9LG",
        "BA12 9LH",
        "BA12 9LJ",
        "BA12 9LL",
        "BA12 9LQ",
        "BA12 9LR",
        "BA12 9LY",
        "BA12 9LZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.176,
              51.201
            ],
            [
              -2.1639,
              51.201
            ],
            [
              -2.1639,
              51.1944
            ],
            [
              -2.176,
              51.1944
            ],
            [
              -2.176,
              51.201
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-10T15:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.201,
      "etrUpdate": true
    },
    {
      "latitude": 51.51126235098664,
      "type": "LV",
      "reference": "KN4117",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-10T19:05:00.000+0000",
      "affectedCustomerCount": 6,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "11f09d9e-5417-4de2-815b-bca15dc35590",
      "minLongitude": -0.7443,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7420768486817083,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-10T16:24:00.000+0000",
      "estimatedRestoration": "2023-02-11T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4117'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4117",
      "maxLongitude": -0.7412,
      "minLatitude": 51.5093,
      "name": "SL6 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL6 4AY",
        "SL6 4BG",
        "SL6 4BQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7443,
              51.5142
            ],
            [
              -0.7412,
              51.5142
            ],
            [
              -0.7412,
              51.5093
            ],
            [
              -0.7443,
              51.5093
            ],
            [
              -0.7443,
              51.5142
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-10T19:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5142,
      "etrUpdate": true
    },
    {
      "latitude": 50.993284676049576,
      "type": "LV",
      "reference": "KN4281",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-11T04:45:00.000+0000",
      "affectedCustomerCount": 1,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9d7a619e-b8e6-48a1-b99e-b66004cbe303",
      "minLongitude": -2.6114,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.606832931323032,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T05:10:00.000+0000",
      "estimatedRestoration": "2023-02-11T14:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4281'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4281",
      "maxLongitude": -2.5961,
      "minLatitude": 50.9846,
      "name": "BA22 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BA22 8BQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6114,
              50.9967
            ],
            [
              -2.5961,
              50.9967
            ],
            [
              -2.5961,
              50.9846
            ],
            [
              -2.6114,
              50.9846
            ],
            [
              -2.6114,
              50.9967
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9967,
      "etrUpdate": true
    },
    {
      "latitude": 51.51435021023685,
      "type": "LV",
      "reference": "KN4338",
      "etaUpdate": true,
      "affectedCustomerCount": 29,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "9884c26f-ddf7-4cdc-a4a8-774309d8bc90",
      "minLongitude": -0.38,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3782979287474611,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T09:55:00.000+0000",
      "estimatedRestoration": "2023-02-11T15:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4338'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4338",
      "maxLongitude": -0.3766,
      "minLatitude": 51.5132,
      "name": "UB1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "UB1 2AF",
        "UB1 2AH",
        "UB1 2AJ",
        "UB1 2AP",
        "UB1 2AW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.38,
              51.5163
            ],
            [
              -0.3766,
              51.5163
            ],
            [
              -0.3766,
              51.5132
            ],
            [
              -0.38,
              51.5132
            ],
            [
              -0.38,
              51.5163
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-11T11:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5163,
      "etrUpdate": true
    },
    {
      "latitude": 51.51126235098664,
      "type": "LV",
      "reference": "KN4352",
      "etaUpdate": true,
      "affectedCustomerCount": 6,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "5bf4136d-9e66-42e8-9ebb-2daf803f5798",
      "minLongitude": -0.7443,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7420768486817083,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T10:34:00.000+0000",
      "estimatedRestoration": "2023-02-11T14:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4352'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4352",
      "maxLongitude": -0.7412,
      "minLatitude": 51.5093,
      "name": "SL6 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL6 4AY",
        "SL6 4BG",
        "SL6 4BQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7443,
              51.5142
            ],
            [
              -0.7412,
              51.5142
            ],
            [
              -0.7412,
              51.5093
            ],
            [
              -0.7443,
              51.5093
            ],
            [
              -0.7443,
              51.5142
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-11T11:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5142,
      "etrUpdate": true
    },
    {
      "latitude": 50.84077003960007,
      "type": "LV",
      "reference": "KN4364",
      "etaUpdate": true,
      "affectedCustomerCount": 20,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a8d1c53a-88ea-4147-b29c-92159b4e720d",
      "minLongitude": -0.7714,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7700034866150511,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T11:00:00.000+0000",
      "estimatedRestoration": "2023-02-11T14:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4364'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4364",
      "maxLongitude": -0.7691,
      "minLatitude": 50.84,
      "name": "PO19 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO19 6SQ",
        "PO19 7AU",
        "PO19 7AX",
        "PO19 7NA",
        "PO19 7NB",
        "PO19 7WS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7714,
              50.8416
            ],
            [
              -0.7691,
              50.8416
            ],
            [
              -0.7691,
              50.84
            ],
            [
              -0.7714,
              50.84
            ],
            [
              -0.7714,
              50.8416
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-11T12:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8416,
      "etrUpdate": true
    },
    {
      "latitude": 50.791839670422775,
      "type": "LV",
      "reference": "KM8156",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-02-11T10:00:00.000+0000",
      "affectedCustomerCount": 60,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "6e4a7c3d-5589-4065-87ad-362492a33b98",
      "minLongitude": -1.0548,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.05121517377308,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T10:45:00.000+0000",
      "estimatedRestoration": "2023-02-11T14:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KM8156'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KM8156",
      "maxLongitude": -1.0459,
      "minLatitude": 50.7903,
      "name": "PO4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO4 8EY",
        "PO4 8EZ",
        "PO4 8HF",
        "PO4 8HG",
        "PO4 8HJ",
        "PO4 8HL",
        "PO4 8HN",
        "PO4 8HP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0548,
              50.7929
            ],
            [
              -1.0459,
              50.7929
            ],
            [
              -1.0459,
              50.7903
            ],
            [
              -1.0548,
              50.7903
            ],
            [
              -1.0548,
              50.7929
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "evChargersAffected": [
        "d7650a0e-e555-4c5f-98a8-4e870d7e1ff6",
        "f2691ee8-8442-49ae-8214-eb1f726e34ac"
      ],
      "maxLatitude": 50.7929,
      "etrUpdate": true
    },
    {
      "latitude": 56.7129423893132,
      "type": "PSI",
      "reference": "213850",
      "etaUpdate": true,
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "64dc9ac7-137f-436c-8ac8-38e3a31947ec",
      "minLongitude": -3.501,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.487175013457337,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T09:00:00.000+0000",
      "estimatedRestoration": "2023-02-11T13:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '213850'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/213850",
      "maxLongitude": -3.4719,
      "minLatitude": 56.7009,
      "name": "PH10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PH10 7NP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.501,
              56.7188
            ],
            [
              -3.4719,
              56.7188
            ],
            [
              -3.4719,
              56.7009
            ],
            [
              -3.501,
              56.7009
            ],
            [
              -3.501,
              56.7188
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.7188,
      "etrUpdate": true
    },
    {
      "latitude": 55.63595041137099,
      "type": "LV",
      "reference": "KN4345",
      "etaUpdate": true,
      "affectedCustomerCount": 5,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "dfb0fa6a-c99b-41fd-9955-8a81bef8f78f",
      "minLongitude": -6.1451,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -6.123183928188987,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-02-11T10:12:00.000+0000",
      "estimatedRestoration": "2023-02-11T13:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KN4345'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KN4345",
      "maxLongitude": -6.1132,
      "minLatitude": 55.6285,
      "name": "PA42 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PA42 7DX",
        "PA42 7DY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.1451,
              55.6467
            ],
            [
              -6.1132,
              55.6467
            ],
            [
              -6.1132,
              55.6285
            ],
            [
              -6.1451,
              55.6285
            ],
            [
              -6.1451,
              55.6467
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-02-11T11:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 55.6467,
      "etrUpdate": true
    }
  ]
}
