{
  "Faults": [
    {
      "latitude": 51.709982534175396,
      "type": "LV",
      "reference": "KJ5373",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T01:45:00.000+0000",
      "affectedCustomerCount": 17,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "32a8f1b1-6220-4216-bc2e-3c79464d617e",
      "minLongitude": -1.9677,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.963336601334915,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T11:02:00.000+0000",
      "estimatedRestoration": "2023-01-03T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5373'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5373",
      "maxLongitude": -1.9614,
      "minLatitude": 51.7083,
      "name": "GL7 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GL7 1JU",
        "GL7 1JX",
        "GL7 1NA",
        "GL7 1NE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9677,
              51.712
            ],
            [
              -1.9614,
              51.712
            ],
            [
              -1.9614,
              51.7083
            ],
            [
              -1.9677,
              51.7083
            ],
            [
              -1.9677,
              51.712
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T02:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.712,
      "etrUpdate": true
    },
    {
      "latitude": 51.28376048430695,
      "type": "LV",
      "reference": "KJ5429",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T09:05:00.000+0000",
      "affectedCustomerCount": 27,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "464d8b7b-e2d9-4289-8ea7-b8899dabb99d",
      "minLongitude": -0.9527,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9489184052387352,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T08:11:00.000+0000",
      "estimatedRestoration": "2023-01-03T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5429'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5429",
      "maxLongitude": -0.9456,
      "minLatitude": 51.2806,
      "name": "RG27 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "RG27 9EN",
        "RG27 9EP",
        "RG27 9EW",
        "RG27 9LQ",
        "RG27 9RY",
        "RG27 9RZ",
        "RG27 9SD",
        "RG27 9SE",
        "RG27 9SF",
        "RG27 9UA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.9527,
              51.2867
            ],
            [
              -0.9456,
              51.2867
            ],
            [
              -0.9456,
              51.2806
            ],
            [
              -0.9527,
              51.2806
            ],
            [
              -0.9527,
              51.2867
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T09:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2867,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T07:50:00.000+0000",
      "latitude": 51.504087836722285,
      "estimatedRestoration": "2023-01-03T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5418'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5418",
      "reference": "KJ5418",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T09:00:00.000+0000",
      "affectedCustomerCount": 12,
      "name": "UB7 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB7 9AD",
        "UB7 9AE",
        "UB7 9LF",
        "UB7 9LR"
      ],
      "location": {
        "coordinates": [
          -0.45950932930096494,
          51.504087836722285
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T09:00:00.000+0000",
      "UUID": "1b05b130-bc35-45ad-857c-ed7766336854",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -0.45950932930096494,
      "resolved": false
    },
    {
      "latitude": 51.540042836640886,
      "type": "LV",
      "reference": "KJ5474",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T11:00:00.000+0000",
      "affectedCustomerCount": 10,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "1a67f9ce-dcee-472b-ad3f-3bc5f3ac0afc",
      "minLongitude": -1.9085,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9063017920902292,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T09:13:00.000+0000",
      "estimatedRestoration": "2023-01-03T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5474'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5474",
      "maxLongitude": -1.9045,
      "minLatitude": 51.5386,
      "name": "SN4 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SN4 7AB",
        "SN4 7BS",
        "SN4 7BT",
        "SN4 7BU",
        "SN4 7BZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9085,
              51.5417
            ],
            [
              -1.9045,
              51.5417
            ],
            [
              -1.9045,
              51.5386
            ],
            [
              -1.9085,
              51.5386
            ],
            [
              -1.9085,
              51.5417
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.5417,
      "etrUpdate": true
    },
    {
      "latitude": 50.64067002008125,
      "type": "HV",
      "reference": "KJ5680",
      "etaUpdate": true,
      "affectedCustomerCount": 71,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "44a11a09-5688-448b-8b49-2d6930ebff1e",
      "minLongitude": -1.9582,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9478916573582814,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T09:42:00.000+0000",
      "estimatedRestoration": "2023-01-03T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5680'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5680",
      "maxLongitude": -1.9312,
      "minLatitude": 50.6271,
      "name": "BH19 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH19 3AL",
        "BH19 3AN",
        "BH19 3AS",
        "BH19 3AT",
        "BH19 3AU",
        "BH19 3AW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.9582,
              50.6454
            ],
            [
              -1.9312,
              50.6454
            ],
            [
              -1.9312,
              50.6271
            ],
            [
              -1.9582,
              50.6271
            ],
            [
              -1.9582,
              50.6454
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T13:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.6454,
      "etrUpdate": true
    },
    {
      "latitude": 51.30785539755546,
      "type": "LV",
      "reference": "KJ5769",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T14:30:00.000+0000",
      "affectedCustomerCount": 39,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "16978395-7d9e-4d65-8af1-705eae8ed59f",
      "minLongitude": -0.7857,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7814750104475879,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T13:28:00.000+0000",
      "estimatedRestoration": "2023-01-03T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5769'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5769",
      "maxLongitude": -0.7778,
      "minLatitude": 51.3057,
      "name": "GU14 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU14 9GQ",
        "GU14 9GU",
        "GU14 9HE",
        "GU14 9HJ",
        "GU14 9HU",
        "GU14 9HX",
        "GU14 9HY",
        "GU14 9HZ",
        "GU14 9JA",
        "GU14 9JB",
        "GU14 9JD",
        "GU14 9JE",
        "GU14 9JF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7857,
              51.3131
            ],
            [
              -0.7778,
              51.3131
            ],
            [
              -0.7778,
              51.3057
            ],
            [
              -0.7857,
              51.3057
            ],
            [
              -0.7857,
              51.3131
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T14:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3131,
      "etrUpdate": true
    },
    {
      "latitude": 51.374733444766804,
      "type": "LV",
      "reference": "KJ5675",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T12:30:00.000+0000",
      "affectedCustomerCount": 3,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d87d5b8d-25c6-4fd6-a8fc-34b27c77b944",
      "minLongitude": -0.6682,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.662259853153129,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T11:48:00.000+0000",
      "estimatedRestoration": "2023-01-03T18:45:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5675'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5675",
      "maxLongitude": -0.6537,
      "minLatitude": 51.3691,
      "name": "GU20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU20 6AD",
        "GU20 6LA",
        "GU20 6LJ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6682,
              51.3813
            ],
            [
              -0.6537,
              51.3813
            ],
            [
              -0.6537,
              51.3691
            ],
            [
              -0.6682,
              51.3691
            ],
            [
              -0.6682,
              51.3813
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3813,
      "etrUpdate": true
    },
    {
      "latitude": 51.75750318234167,
      "type": "HV",
      "reference": "KJ5843",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-01-03T14:00:00.000+0000",
      "affectedCustomerCount": 4,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "510c3432-ed22-42f1-aef7-185ab264e250",
      "minLongitude": -1.2501,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.2481972505244956,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T13:24:00.000+0000",
      "estimatedRestoration": "2023-01-03T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5843'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5843",
      "maxLongitude": -1.245,
      "minLatitude": 51.7567,
      "name": "OX1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX1 3TJ",
        "OX1 3TR",
        "OX1 3UR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.2501,
              51.7615
            ],
            [
              -1.245,
              51.7615
            ],
            [
              -1.245,
              51.7567
            ],
            [
              -1.2501,
              51.7567
            ],
            [
              -1.2501,
              51.7615
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.7615,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T14:40:00.000+0000",
      "latitude": 51.51366660491952,
      "estimatedRestoration": "2023-01-03T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5851'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5851",
      "reference": "KJ5851",
      "etaUpdate": true,
      "affectedCustomerCount": 30,
      "name": "UB7 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "UB7 7BB",
        "UB7 7BD",
        "UB7 7BG",
        "UB7 7BH",
        "UB7 7QL",
        "UB7 7RL"
      ],
      "location": {
        "coordinates": [
          -0.4734249278384852,
          51.51366660491952
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T16:30:00.000+0000",
      "UUID": "7e3a14d6-347e-4a4f-8091-98101999df9b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -0.4734249278384852,
      "resolved": false
    },
    {
      "latitude": 51.49263485773506,
      "type": "LV",
      "reference": "KJ5720",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d03a3c9c-5ae1-4387-8b46-52a134ac3e90",
      "minLongitude": -0.3142,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.31084567512178973,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T12:33:00.000+0000",
      "estimatedRestoration": "2023-01-03T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5720'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5720",
      "maxLongitude": -0.3073,
      "minLatitude": 51.4904,
      "name": "W5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW8 9LZ",
        "TW8 9NH",
        "TW8 9NQ",
        "W5 4BJ",
        "W5 4BP",
        "W5 4BS",
        "W5 4BT",
        "W5 4XP"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3142,
              51.4951
            ],
            [
              -0.3073,
              51.4951
            ],
            [
              -0.3073,
              51.4904
            ],
            [
              -0.3142,
              51.4904
            ],
            [
              -0.3142,
              51.4951
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T16:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "evChargersAffected": [
        "399a296c-cfb9-4073-9a41-27bdc67ccc80",
        "a4738650-9511-4b73-8013-aa21bc2ea26a",
        "f65c9582-a617-4f41-958b-883afc0c0d89"
      ],
      "maxLatitude": 51.4951,
      "etrUpdate": true
    },
    {
      "latitude": 51.252498302212025,
      "type": "LV",
      "reference": "KH9577",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "46b4ee85-b801-4017-9bd8-5028e0d32626",
      "minLongitude": -0.7371,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7347774914397431,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T12:45:00.000+0000",
      "estimatedRestoration": "2023-01-03T17:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KH9577'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KH9577",
      "maxLongitude": -0.733,
      "minLatitude": 51.2496,
      "name": "GU12 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU12 4UG",
        "GU12 4UJ",
        "GU12 4UN",
        "GU12 4UQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.7371,
              51.2541
            ],
            [
              -0.733,
              51.2541
            ],
            [
              -0.733,
              51.2496
            ],
            [
              -0.7371,
              51.2496
            ],
            [
              -0.7371,
              51.2541
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.2541,
      "etrUpdate": true
    },
    {
      "latitude": 51.61698612814213,
      "type": "HV",
      "reference": "KJ5896",
      "etaUpdate": true,
      "affectedCustomerCount": 77,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "4399ee60-75e4-4187-b5ce-82a131ea30d5",
      "minLongitude": -1.1199,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.111704009626655,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T14:49:00.000+0000",
      "estimatedRestoration": "2023-01-03T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5896'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5896",
      "maxLongitude": -1.1051,
      "minLatitude": 51.6087,
      "name": "OX10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "OX10 6RY",
        "OX10 6SE",
        "OX10 6SF",
        "OX10 6SL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.1199,
              51.6209
            ],
            [
              -1.1051,
              51.6209
            ],
            [
              -1.1051,
              51.6087
            ],
            [
              -1.1199,
              51.6087
            ],
            [
              -1.1199,
              51.6209
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.6209,
      "etrUpdate": true
    },
    {
      "latitude": 56.82971782900201,
      "type": "HV",
      "reference": "KJ5846",
      "etaUpdate": true,
      "affectedCustomerCount": 11,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "dfc66f92-f62c-40d7-ba2c-75e48381c3e0",
      "minLongitude": -2.3532,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.3314751666570803,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-01-03T14:43:00.000+0000",
      "estimatedRestoration": "2023-01-03T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KJ5846'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KJ5846",
      "maxLongitude": -2.3088,
      "minLatitude": 56.8156,
      "name": "DD10 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD10 0HX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3532,
              56.8464
            ],
            [
              -2.3088,
              56.8464
            ],
            [
              -2.3088,
              56.8156
            ],
            [
              -2.3532,
              56.8156
            ],
            [
              -2.3532,
              56.8464
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-01-03T15:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.8464,
      "etrUpdate": true
    }
  ]
}
