{
  "Faults": [
    {
      "latitude": 50.917694770128094,
      "type": "LV",
      "reference": "KG1287",
      "etaUpdate": true,
      "engineerOnSiteTime": "2022-12-01T14:30:00.000+0000",
      "affectedCustomerCount": 30,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "11ad94bb-3cff-4a0c-b011-3f16ca469949",
      "minLongitude": -1.3506,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3464211854351296,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T21:00:00.000+0000",
      "estimatedRestoration": "2022-12-02T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1287'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1287",
      "maxLongitude": -1.3424,
      "minLatitude": 50.9159,
      "name": "SO18 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SO18 5BU",
        "SO18 5BW",
        "SO18 5BX",
        "SO18 5BY",
        "SO18 5DB",
        "SO18 5DD",
        "SO18 5DE",
        "SO18 5DF",
        "SO18 5DG",
        "SO18 5DH",
        "SO18 5FP",
        "SO18 5LA"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3506,
              50.9198
            ],
            [
              -1.3424,
              50.9198
            ],
            [
              -1.3424,
              50.9159
            ],
            [
              -1.3506,
              50.9159
            ],
            [
              -1.3506,
              50.9198
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-12-01T16:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.9198,
      "etrUpdate": true
    },
    {
      "latitude": 50.750695682265,
      "type": "LV",
      "reference": "KG1532",
      "etaUpdate": true,
      "affectedCustomerCount": 40,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "a4b948f0-3ace-4be0-bc10-1f394aa9ae3c",
      "minLongitude": -1.8793,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8761300439351054,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T20:30:00.000+0000",
      "estimatedRestoration": "2022-12-01T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1532'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1532",
      "maxLongitude": -1.8724,
      "minLatitude": 50.7433,
      "name": "BH9 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH9 1TN",
        "BH9 1TS",
        "BH9 1TW",
        "BH9 2AX",
        "BH9 2BA",
        "BH9 2BD",
        "BH9 2BE",
        "BH9 2BG",
        "BH9 2DH",
        "BH9 2EY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8793,
              50.7549
            ],
            [
              -1.8724,
              50.7549
            ],
            [
              -1.8724,
              50.7433
            ],
            [
              -1.8793,
              50.7433
            ],
            [
              -1.8793,
              50.7549
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-12-01T21:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7549,
      "etrUpdate": true
    },
    {
      "latitude": 50.79041520606902,
      "type": "LV",
      "reference": "KG1548",
      "etaUpdate": true,
      "affectedCustomerCount": 19,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "6e8c0e9f-7e08-4aca-bc71-853884365ffe",
      "minLongitude": -1.0913,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0891241620824748,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T21:16:00.000+0000",
      "estimatedRestoration": "2022-12-02T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1548'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1548",
      "maxLongitude": -1.0865,
      "minLatitude": 50.7897,
      "name": "PO5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO5",
        "PO5 1JE",
        "PO5 1JF",
        "PO5 1JG",
        "PO5 1JY",
        "PO5 1JZ",
        "PO5 1NB",
        "PO5 3EB"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0913,
              50.7911
            ],
            [
              -1.0865,
              50.7911
            ],
            [
              -1.0865,
              50.7897
            ],
            [
              -1.0913,
              50.7897
            ],
            [
              -1.0913,
              50.7911
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-12-01T21:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7911,
      "etrUpdate": true
    },
    {
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T21:31:00.000+0000",
      "latitude": 50.994724162042914,
      "estimatedRestoration": "2022-12-02T00:35:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1550'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1550",
      "reference": "KG1550",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "name": "SO51 Area",
      "otherUpdate": true,
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO51 8FJ",
        "SO51 8FL"
      ],
      "location": {
        "coordinates": [
          -1.5015268253510752,
          50.994724162042914
        ],
        "type": "Point"
      },
      "UUID": "0761dd37-b9a7-4cc1-b060-55463222160d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "etrUpdate": true,
      "longitude": -1.5015268253510752,
      "resolved": false
    },
    {
      "latitude": 57.67632282182494,
      "type": "LV",
      "reference": "KG1462",
      "etaUpdate": true,
      "affectedCustomerCount": 12,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "1b34c5fd-6bd0-4af7-bafa-fdb5839fb2cf",
      "minLongitude": -2.9571,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.9550653117566013,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T16:31:00.000+0000",
      "estimatedRestoration": "2022-12-01T23:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1462'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1462",
      "maxLongitude": -2.9527,
      "minLatitude": 57.6755,
      "name": "AB56 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "AB56 1ND",
        "AB56 1NN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.9571,
              57.6772
            ],
            [
              -2.9527,
              57.6772
            ],
            [
              -2.9527,
              57.6755
            ],
            [
              -2.9571,
              57.6755
            ],
            [
              -2.9571,
              57.6772
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-12-01T17:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 57.6772,
      "etrUpdate": true
    },
    {
      "latitude": 58.42639435242859,
      "type": "HV",
      "reference": "KG1516",
      "etaUpdate": true,
      "affectedCustomerCount": 136,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "055d2036-d7ba-4753-a567-d6074db655e4",
      "minLongitude": -3.1363,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0913872909066353,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2022-12-01T19:15:00.000+0000",
      "estimatedRestoration": "2022-12-01T22:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'KG1516'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/KG1516",
      "maxLongitude": -3.0624,
      "minLatitude": 58.3971,
      "name": "KW1 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "KW1 5BF",
        "KW1 5BY",
        "KW1 5TF",
        "KW1 5TG",
        "KW1 5TH",
        "KW1 5TJ",
        "KW1 5TL",
        "KW1 5TN",
        "KW1 5TP",
        "KW1 5TY"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.1363,
              58.439
            ],
            [
              -3.0624,
              58.439
            ],
            [
              -3.0624,
              58.3971
            ],
            [
              -3.1363,
              58.3971
            ],
            [
              -3.1363,
              58.439
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-12-01T20:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 58.439,
      "etrUpdate": true
    }
  ]
}
