{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T12:52:00.000+0000",
      "latitude": 50.879777715613784,
      "estimatedRestoration": "2022-09-05T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5310'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5310",
      "reference": "JZ5310",
      "maxLongitude": -1.0255,
      "engineerOnSiteTime": "2022-09-04T13:19:00.000+0000",
      "minLatitude": 50.8777,
      "name": "PO7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO7 7DS",
        "PO7 7DT",
        "PO7 7DU",
        "PO7 7DZ",
        "PO7 7FH",
        "PO7 7HA",
        "PO7 7JJ",
        "PO7 7JL",
        "PO7 7JN",
        "PO7 7JR",
        "PO7 7NT"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.0322,
              50.8831
            ],
            [
              -1.0255,
              50.8831
            ],
            [
              -1.0255,
              50.8777
            ],
            [
              -1.0322,
              50.8777
            ],
            [
              -1.0322,
              50.8831
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "f7ca56e4-1b18-466d-99a0-95bc7a9d68d6",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.0322,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8831,
      "longitude": -1.0291041810368535,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T15:28:00.000+0000",
      "latitude": 51.717174789714804,
      "estimatedRestoration": "2022-09-05T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5348'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5348",
      "reference": "JZ5348",
      "maxLongitude": -1.5795,
      "engineerOnSiteTime": "2022-09-04T16:30:00.000+0000",
      "minLatitude": 51.7151,
      "name": "OX18 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX18 2PA",
        "OX18 2PB",
        "OX18 2QZ",
        "OX18 2RB",
        "OX18 2RG",
        "OX18 2RU"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.5989,
              51.7249
            ],
            [
              -1.5795,
              51.7249
            ],
            [
              -1.5795,
              51.7151
            ],
            [
              -1.5989,
              51.7151
            ],
            [
              -1.5989,
              51.7249
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "4dc165c5-4764-4e53-802d-9ab0325af2c4",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.5989,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.7249,
      "longitude": -1.589526125034215,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T21:50:00.000+0000",
      "latitude": 51.76207875996703,
      "estimatedRestoration": "2022-09-04T22:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5353'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5353",
      "reference": "JZ5353",
      "maxLongitude": -1.2238,
      "engineerOnSiteTime": "2022-09-04T17:30:00.000+0000",
      "minLatitude": 51.7612,
      "name": "OX3 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX3 7SZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.2257,
              51.7629
            ],
            [
              -1.2238,
              51.7629
            ],
            [
              -1.2238,
              51.7612
            ],
            [
              -1.2257,
              51.7612
            ],
            [
              -1.2257,
              51.7629
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "a60a5c4d-289c-43b5-9917-74c3f4330efc",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.2257,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.7629,
      "longitude": -1.2245175405121398,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T22:54:00.000+0000",
      "latitude": 51.36341733894162,
      "estimatedRestoration": "2022-09-05T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5470'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5470",
      "reference": "JZ5470",
      "maxLongitude": -2.0852,
      "minLatitude": 51.3588,
      "name": "SN12 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN12 6RF"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.1115,
              51.377
            ],
            [
              -2.0852,
              51.377
            ],
            [
              -2.0852,
              51.3588
            ],
            [
              -2.1115,
              51.3588
            ],
            [
              -2.1115,
              51.377
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-09-04T23:45:00.000+0000",
      "UUID": "b1ed3a18-c186-449b-80b0-f7e431e5a072",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.1115,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.377,
      "longitude": -2.0992155839043387,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T23:05:00.000+0000",
      "latitude": 50.88642778370898,
      "estimatedRestoration": "2022-09-05T02:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5474'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5474",
      "reference": "JZ5474",
      "maxLongitude": -1.3159,
      "minLatitude": 50.8797,
      "name": "SO31 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO31 8DE",
        "SO31 8FL",
        "SO31 8FN"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.3215,
              50.8896
            ],
            [
              -1.3159,
              50.8896
            ],
            [
              -1.3159,
              50.8797
            ],
            [
              -1.3215,
              50.8797
            ],
            [
              -1.3215,
              50.8896
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-09-05T00:15:00.000+0000",
      "UUID": "e25c0f72-ab6d-417d-9bb6-452f598cf8e8",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.3215,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 50.8896,
      "longitude": -1.3181132755218001,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T23:26:00.000+0000",
      "latitude": 51.562171753092784,
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5484'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5484",
      "reference": "JZ5484",
      "maxLongitude": -1.0588,
      "minLatitude": 51.5328,
      "name": "OX10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX10 6AD",
        "OX10 6AE",
        "OX10 6AF",
        "OX10 6AG",
        "OX10 6AH",
        "OX10 6AJ",
        "OX10 6AL",
        "OX10 6AN",
        "OX10 6AP",
        "OX10 6AQ",
        "OX10 6AR",
        "OX10 6AS",
        "OX10 6AU",
        "OX10 6AW",
        "OX10 6AX",
        "OX10 6AY",
        "OX10 6AZ",
        "OX10 6BA",
        "OX10 6BB",
        "OX10 6BD",
        "OX10 6BG",
        "OX10 6BH",
        "OX10 6BL",
        "OX10 6BN",
        "OX10 6BP",
        "OX10 6BQ",
        "OX10 6BS",
        "OX10 6BU",
        "OX10 6BW",
        "OX10 6BZ",
        "OX10 6ET",
        "OX10 6JE",
        "OX10 6QZ",
        "OX10 8BP",
        "OX10 8BS",
        "OX10 8BU",
        "OX10 8BX",
        "OX10 8DA",
        "OX10 8DD",
        "OX10 8DY",
        "OX10 8EJ",
        "OX10 9EX",
        "OX10 9HP",
        "OX10 9HR",
        "OX10 9HS",
        "OX10 9HT",
        "OX10 9HU",
        "OX10 9HW",
        "OX10 9HX",
        "OX10 9HZ",
        "OX10 9JA",
        "OX10 9JB",
        "OX10 9JD",
        "OX10 9JE",
        "OX10 9JF",
        "OX10 9JG",
        "OX10 9JH",
        "OX10 9JJ",
        "OX10 9JL",
        "OX10 9JQ",
        "OX10 9JR",
        "OX10 9JS",
        "OX10 9JT",
        "OX10 9JU",
        "OX10 9LU",
        "RG8 0LX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.201,
              51.6359
            ],
            [
              -1.0588,
              51.6359
            ],
            [
              -1.0588,
              51.5328
            ],
            [
              -1.201,
              51.5328
            ],
            [
              -1.201,
              51.6359
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "bc4207a5-482d-4239-aeb5-2bdc75062813",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -1.201,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 51.6359,
      "longitude": -1.121023931297056,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T18:16:00.000+0000",
      "latitude": 58.58075781827697,
      "estimatedRestoration": "2022-09-05T00:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5417'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5417",
      "reference": "JZ5417",
      "maxLongitude": -3.1374,
      "minLatitude": 58.4799,
      "name": "KW14 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW1 4TL",
        "KW1 4TN",
        "KW1 4TP",
        "KW1 4TS",
        "KW1 4TT",
        "KW1 4TW",
        "KW1 4UD",
        "KW1 5BU",
        "KW1 5UP",
        "KW1 5UR",
        "KW1 5UT",
        "KW1 5UU",
        "KW1 5UW",
        "KW12 6UX",
        "KW12 6UY",
        "KW12 6UZ",
        "KW14",
        "KW14 7JA",
        "KW14 7RY",
        "KW14 7XQ",
        "KW14 7YD",
        "KW14 8AP",
        "KW14 8HL",
        "KW14 8SL",
        "KW14 8SN",
        "KW14 8SW",
        "KW14 8SX",
        "KW14 8SY",
        "KW14 8SZ",
        "KW14 8TA",
        "KW14 8TB",
        "KW14 8TD",
        "KW14 8TE",
        "KW14 8TP",
        "KW14 8UA",
        "KW14 8XD",
        "KW14 8XE",
        "KW14 8XF",
        "KW14 8XG",
        "KW14 8XN",
        "KW14 8XP",
        "KW14 8XQ",
        "KW14 8XR",
        "KW14 8XS",
        "KW14 8XT",
        "KW14 8XW",
        "KW14 8YD",
        "KW14 8YE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -4.0684,
              58.6726
            ],
            [
              -3.1374,
              58.6726
            ],
            [
              -3.1374,
              58.4799
            ],
            [
              -4.0684,
              58.4799
            ],
            [
              -4.0684,
              58.6726
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "c4aba4c5-58c2-4be6-aaf3-31e27d95910d",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -4.0684,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 58.6726,
      "longitude": -3.3731712198395516,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T20:30:00.000+0000",
      "latitude": 58.33530921927843,
      "estimatedRestoration": "2022-09-05T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5448'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5448",
      "reference": "JZ5448",
      "maxLongitude": -6.5603,
      "minLatitude": 58.2982,
      "name": "HS2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "HS2 9DA",
        "HS2 9DB",
        "HS2 9DD",
        "HS2 9DE",
        "HS2 9DF",
        "HS2 9DG",
        "HS2 9DQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -6.652,
              58.3633
            ],
            [
              -6.5603,
              58.3633
            ],
            [
              -6.5603,
              58.2982
            ],
            [
              -6.652,
              58.2982
            ],
            [
              -6.652,
              58.3633
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "8a08423e-99d8-46cf-a1c8-ddcad42de10f",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -6.652,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 58.3633,
      "longitude": -6.626193963082226,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-09-04T22:44:00.000+0000",
      "latitude": 56.72843269083951,
      "estimatedRestoration": "2022-09-05T02:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JZ5465'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JZ5465",
      "reference": "JZ5465",
      "maxLongitude": -2.6499,
      "minLatitude": 56.7266,
      "name": "DD9 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD9 7BX",
        "DD9 7BY",
        "DD9 7BZ",
        "DD9 7DD",
        "DD9 7DJ",
        "DD9 7DL"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.6543,
              56.7297
            ],
            [
              -2.6499,
              56.7297
            ],
            [
              -2.6499,
              56.7266
            ],
            [
              -2.6543,
              56.7266
            ],
            [
              -2.6543,
              56.7297
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "a68b70d2-b390-4705-8613-ddd8290f370a",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -2.6543,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "maxLatitude": 56.7297,
      "longitude": -2.6514655810271313,
      "resolved": false
    }
  ]
}
