{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-08-12T23:03:00.000+0000",
      "latitude": 51.507909106322174,
      "estimatedRestoration": "2022-08-13T11:00:00.000+0000",
      "message": "Weâ€™re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JY2225'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JY2225",
      "reference": "JY2225",
      "maxLongitude": -0.3341,
      "minLatitude": 51.5067,
      "name": "W7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "W7 3PN",
        "W7 3SH",
        "W7 3SJ",
        "W7 3SQ",
        "W7 3SU",
        "W7 3SW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3381,
              51.5088
            ],
            [
              -0.3341,
              51.5088
            ],
            [
              -0.3341,
              51.5067
            ],
            [
              -0.3381,
              51.5067
            ],
            [
              -0.3381,
              51.5088
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "595201c8-b0aa-4286-bc47-a45e641a0d7b",
      "region": "com.opengrid.geo.world.europe.gb",
      "minLongitude": -0.3381,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "d97792a9-a2b4-4d79-87f4-bb61fc95d44d"
      ],
      "maxLatitude": 51.5088,
      "longitude": -0.337011479042319,
      "resolved": false
    }
  ]
}
