{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-06-04T15:57:00.000+0000",
      "latitude": 50.920076924708326,
      "estimatedRestoration": "2022-06-04T19:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JU2172'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JU2172",
      "reference": "JU2172",
      "name": "BA22 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA22 9UL",
        "BA22 9UW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.6172325292173637,
          50.920076924708326
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-06-04T17:30:00.000+0000",
      "UUID": "5ef8decd-50aa-44a1-b35e-d235e8625dbd",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.6172325292173637,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-06-04T17:45:00.000+0000",
      "latitude": 51.45772054836123,
      "estimatedRestoration": "2022-06-04T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JU2196'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JU2196",
      "reference": "JU2196",
      "name": "TW7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "TW7 7QJ",
        "TW7 7QP",
        "TW7 7QR",
        "TW7 7QU",
        "TW7 7QW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.33241630536598493,
          51.45772054836123
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-06-04T19:00:00.000+0000",
      "UUID": "58e4458d-c005-4c94-83c2-5d3f2f68885e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.33241630536598493,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-06-04T10:42:00.000+0000",
      "latitude": 57.479500979415214,
      "estimatedRestoration": "2022-06-04T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on their way to site to get the power back on as quickly as they can. please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JU2068'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JU2068",
      "reference": "JU2068",
      "name": "IV3 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV3 5HS",
        "IV3 5JA",
        "IV3 5JD",
        "IV3 5JJ",
        "IV3 5JL",
        "IV3 5PN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -4.233348109034516,
          57.479500979415214
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-06-04T11:30:00.000+0000",
      "UUID": "49198171-00b6-479c-89c6-29e0a9745868",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -4.233348109034516,
      "resolved": false
    }
  ]
}
