{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-14T08:30:00.000+0000",
      "latitude": 51.50575824001529,
      "estimatedRestoration": "2022-03-18T16:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206219'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206219",
      "reference": "206219",
      "name": "SN14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN14 6BJ",
        "SN14 6DG",
        "SN14 6HE",
        "SN14 6JE",
        "SN14 6JF",
        "SN14 6JG",
        "SN14 6JH",
        "SN14 6JJ",
        "SN14 6JL",
        "SN14 6JN",
        "SN14 6JP",
        "SN14 6JQ",
        "SN14 6JW",
        "SN14 6LD",
        "SN14 6LE",
        "SN14 6NH",
        "SN14 6PS",
        "SN14 6PU",
        "SN14 6QL",
        "SN14 6RF",
        "SN14 6RL",
        "SN14 7NA",
        "SN14 8RS"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.160254865602929,
          51.50575824001529
        ],
        "type": "Point"
      },
      "UUID": "3fa8bbb9-cfb1-487c-b7a4-b25d051dd09d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.160254865602929,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T08:00:00.000+0000",
      "latitude": 50.819114379997195,
      "estimatedRestoration": "2022-03-21T17:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206523'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206523",
      "reference": "206523",
      "name": "DT11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT11 9DH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.1515012825925037,
          50.819114379997195
        ],
        "type": "Point"
      },
      "UUID": "f011c6a7-f0bb-453e-881f-bc5e70d1db92",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1515012825925037,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T10:33:00.000+0000",
      "latitude": 51.495898812250765,
      "estimatedRestoration": "2022-03-17T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2030'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2030",
      "reference": "JQ2030",
      "engineerOnSiteTime": "2022-03-17T11:20:00.000+0000",
      "name": "W4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "W3 9EZ",
        "W3 9HB",
        "W4 1SE",
        "W4 1SY",
        "W4 2JD",
        "W4 2LN",
        "W4 2LP",
        "W4 2LR",
        "W4 2LS",
        "W4 2LT",
        "W4 2LW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.25433871884329484,
          51.495898812250765
        ],
        "type": "Point"
      },
      "UUID": "1dd8b3d1-cab4-48e5-84cf-59ae2f07a7dd",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.25433871884329484,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T12:37:00.000+0000",
      "latitude": 51.52604404357847,
      "estimatedRestoration": "2022-03-18T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2133'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2133",
      "reference": "JQ2133",
      "name": "SN14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN14 6BE",
        "SN14 6BN",
        "SN14 6BS",
        "SN14 6BW",
        "SN14 6BX",
        "SN14 6BY",
        "SN14 6DB",
        "SN14 6DW"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.121983923037783,
          51.52604404357847
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T17:30:00.000+0000",
      "UUID": "c1bce889-6c1e-42b1-b98d-e59762d3b64d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.121983923037783,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T12:40:00.000+0000",
      "latitude": 51.47450131562151,
      "estimatedRestoration": "2022-03-17T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2161'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2161",
      "reference": "JQ2161",
      "engineerOnSiteTime": "2022-03-17T14:00:00.000+0000",
      "name": "TW7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "TW7 4AW",
        "TW7 4EJ",
        "TW7 4EP",
        "TW7 4EW",
        "TW7 4EY",
        "TW7 4FH",
        "TW7 4HG",
        "TW7 4HH",
        "TW7 4HQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.34518157276841316,
          51.47450131562151
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T13:40:00.000+0000",
      "UUID": "ee79d271-632a-4368-ae9f-6f7a1b12ecc0",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.34518157276841316,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T14:14:00.000+0000",
      "latitude": 51.8083484030968,
      "estimatedRestoration": "2022-03-17T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2198'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2198",
      "reference": "JQ2198",
      "engineerOnSiteTime": "2022-03-17T17:10:00.000+0000",
      "name": "GL54 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GL54 3JL",
        "GL54 3JN",
        "GL54 3JT",
        "GL54 3JW",
        "GL54 3LE",
        "GL54 3LF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.8762754559254804,
          51.8083484030968
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T14:45:00.000+0000",
      "UUID": "1a070c18-00e1-4ad7-ae4c-c9df2f8226d0",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "evChargersAffected": [
        "c4361042-22f6-491e-a2c9-b38e66f7858c",
        "cd06e3aa-1869-4ace-9683-dd00102cd7fa"
      ],
      "longitude": -1.8762754559254804,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T14:21:00.000+0000",
      "latitude": 51.429543089146975,
      "estimatedRestoration": "2022-03-17T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2208'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2208",
      "reference": "JQ2208",
      "engineerOnSiteTime": "2022-03-17T15:18:00.000+0000",
      "name": "RG41 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG41 5NT",
        "RG41 5NU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.8738272335708306,
          51.429543089146975
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T15:10:00.000+0000",
      "UUID": "5b5dbfd4-2f1a-40ed-9c69-c64651a25895",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8738272335708306,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T18:05:00.000+0000",
      "latitude": 51.930600428274616,
      "estimatedRestoration": "2022-03-17T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2311'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2311",
      "reference": "JQ2311",
      "engineerOnSiteTime": "2022-03-17T17:00:00.000+0000",
      "name": "OX7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX7 7BP",
        "OX7 7EE",
        "OX7 7EU",
        "OX7 7HA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.3708954933123323,
          51.930600428274616
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T20:30:00.000+0000",
      "UUID": "5d4168f4-8ff1-4b74-ada1-b418a01a6abb",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3708954933123323,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T18:00:00.000+0000",
      "latitude": 50.899659733743825,
      "estimatedRestoration": "2022-03-17T21:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206755'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206755",
      "reference": "206755",
      "name": "SO14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO14 3PJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.4025451284599295,
          50.899659733743825
        ],
        "type": "Point"
      },
      "UUID": "4d6b7b45-906f-4479-be66-c97cce48f8ed",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4025451284599295,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T17:58:00.000+0000",
      "latitude": 50.95720147431817,
      "estimatedRestoration": "2022-03-17T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2457'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2457",
      "reference": "JQ2457",
      "name": "DT9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT9 4DY",
        "DT9 4DZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.5143720913652747,
          50.95720147431817
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T19:00:00.000+0000",
      "UUID": "d8b7485c-b4ef-4978-833b-e03ab9f5853f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.5143720913652747,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T17:33:00.000+0000",
      "latitude": 51.45493501336307,
      "estimatedRestoration": "2022-03-17T20:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2422'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2422",
      "reference": "JQ2422",
      "name": "RG1 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG1 3DA",
        "RG1 3DD",
        "RG1 3ES",
        "RG1 3JJ",
        "RG1 4AE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.9623643941349963,
          51.45493501336307
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T18:15:00.000+0000",
      "UUID": "124fccbd-dec4-4c61-ba50-f0e80131089e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9623643941349963,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T18:55:00.000+0000",
      "latitude": 51.23814071153266,
      "estimatedRestoration": "2022-03-17T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2499'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2499",
      "reference": "JQ2499",
      "name": "GU9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU9 0LY",
        "GU9 0LZ",
        "GU9 0NE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.7947200934626267,
          51.23814071153266
        ],
        "type": "Point"
      },
      "UUID": "66372d1d-de76-45f7-a29d-9fa6fc7b6ac4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7947200934626267,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T18:31:00.000+0000",
      "latitude": 51.1921153755051,
      "estimatedRestoration": "2022-03-17T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2484'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2484",
      "reference": "JQ2484",
      "name": "GU10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU10 4RH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.8085144013021891,
          51.1921153755051
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T19:00:00.000+0000",
      "UUID": "926e1951-ea9e-4015-b4eb-f633a3272859",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8085144013021891,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-14T10:00:00.000+0000",
      "latitude": 59.11693007695559,
      "estimatedRestoration": "2022-03-21T19:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206022'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206022",
      "reference": "206022",
      "name": "KW17 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW17 2PJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.119189129637787,
          59.11693007695559
        ],
        "type": "Point"
      },
      "UUID": "12c3f463-535e-47d1-a23a-cd851a71c99f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.119189129637787,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T17:19:00.000+0000",
      "latitude": 57.37438254184181,
      "estimatedRestoration": "2022-03-17T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2446'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2446",
      "reference": "JQ2446",
      "name": "AB51 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "AB51 5BA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.43240604533989,
          57.37438254184181
        ],
        "type": "Point"
      },
      "UUID": "257aaff5-85cc-41da-8969-b31019b0c35b",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.43240604533989,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T17:55:00.000+0000",
      "latitude": 56.702897475988834,
      "estimatedRestoration": "2022-03-17T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2444'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2444",
      "reference": "JQ2444",
      "name": "PH36 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH36 4HX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.703488599794528,
          56.702897475988834
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-17T19:15:00.000+0000",
      "UUID": "009f2913-d067-4491-9fdc-9a8a64af09f4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.703488599794528,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T18:32:00.000+0000",
      "latitude": 60.330554566550056,
      "estimatedRestoration": "2022-03-17T23:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2491'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2491",
      "reference": "JQ2491",
      "name": "ZE2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "ZE2 9PP",
        "ZE2 9QJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.259818756153828,
          60.330554566550056
        ],
        "type": "Point"
      },
      "UUID": "070282a4-6fbc-4029-8049-8b83291e5b2c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.259818756153828,
      "resolved": false
    }
  ]
}
